### ISSUE TITLE
The example of uninames method doesn't call uninames

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1019]
See:
https://docs.perl6.org/routine/uninames

**Comment by Altai-man** [comment]
It looks like a just typo, since it works with `uninames` too. But the output is:
```
> dd ‘»ö«’.comb».uninames;
(("RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK",).Seq, ("LATIN SMALL LETTER O WITH DIAERESIS",).Seq, ("LEFT-POINTING DOUBLE ANGLE QUOTATION MARK",).Seq)
```

It looks somewhat cryptic, and the usage of `dd` is not cool too. Somewhat like
```
> "abc".uninames;
(LATIN SMALL LETTER A LATIN SMALL LETTER B LATIN SMALL LETTER C)
> "»ö«".uninames;
(RIGHT-POINTING DOUBLE ANGLE QUOTATION MARK LATIN SMALL LETTER O WITH DIAERESIS LEFT-POINTING DOUBLE ANGLE QUOTATION MARK)
```
with an explanation about what `uninames` actually do will be much better imho.

Ah, also the original writer could have intentions about showing that "uninames" can be emulated with mapping "uniname" on string, it will be good to reflect this in the docs too.

**Comment by jnthn** [comment]
Note that one of the reasons `uninames` exists is because it is *not* equivalent to `.comb.map(*.uniname)` in all cases. `comb` works at grapheme level, meaning that it hands back a sequence of graphemes (which we more informally talk about as "characters"). By contrast, `uniname` and `uninames` work at codepoint level. Here's an example that shows up the difference, which may be useful to include in the docs:

    > say "Ḍ̇".uninames.perl
    ("LATIN CAPITAL LETTER D WITH DOT BELOW", "COMBINING DOT ABOVE").Seq
    > say "Ḍ̇".comb.map(*.uniname).perl
    ("LATIN CAPITAL LETTER D WITH DOT BELOW",).Seq

**Comment by jnthn** [comment]
Oh, and also worth noting the example may have been trying to show something like this:

    > say "Ḍ̇'oh".comb>>.uninames.perl
    (("LATIN CAPITAL LETTER D WITH DOT BELOW", "COMBINING DOT ABOVE").Seq, ("APOSTROPHE",).Seq, ("LATIN SMALL LETTER O",).Seq, ("LATIN SMALL LETTER H",).Seq)

That is, that you can use it to get the names of the codepoints making up each character, grouped as a sublist per character.
