### ISSUE TITLE
Debugging commands are not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#1060]
See: https://docs.perl6.org/programs/01-debugging 
It says:
"Historically others have existed and others are likely to be written in future"

I'm not sure what "Historically others" are, but I think the following should be documented:

+ perl6-debug-m
+ perl6-gdb-m
+ perl6-valgrind-m

**Comment by stmuk** [comment]
I think the idea is that this repo documents the perl 6 language itself and that debugging details are implementation specific and don't belong here but in the modules which are the linked content.  These modules are used to debug perl 6 programs. The three programs you mention are intended to debug problems with the perl 6 rakudo compiler itself (specifically the MoarVM backend).

**Comment by AlexDaniel** [comment]
And this made me realize that we have https://docs.perl6.org/programs.html 😮

**Comment by jnthn** [comment]
Only two of the programs (`perl6-valgrind-m` and `perl6-gdb-m`) are for debugging problems with the compiler/VM (though they are done in such a way that they produce output useful to file with a bug report). The third, `perl6-debug`, is a user-facing debugger for debugging a user's Perl 6 programs; it actually cannot be used to debug Rakudo itself because of the way it works. :-)
