### ISSUE TITLE
Mix/Bag/etc. should say *in bold* that these collections are unordered

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1106]
We already say that it is unordered many times, but we should find a way to make sure that people pay attention to that (so that they won't even possibly have assumptions about the order).

IRC log: https://irclog.perlgeek.de/perl6/2017-01-02#i_13838604

**Comment by toolforger** [comment]
Just link to the appropriate section in the "traps" document.
Links are highlighted, so bold is not needed.

**Comment by shadowcat-mst** [comment]
Could we, when demonstrating methods that return all values, also do something like: (note, pseudocoding because I'd probably get something wrong anyway)

    $ $bag.all;
    [ 1, 3, 2, 4 ] # order is NOT guaranteed

i.e. intentionally show the output out of order with a comment each time

This might help for people who look at the examples and not the words.

**Comment by coke** [comment]
-1 for bold.

+1 for a standardized way to document a collection as ordered vs. unordered.

**Comment by b2gills** [comment]
Actually if the hashing algorithm was randomized like the default for Perl 5 now is, this wouldn't be as big a trap, because it becomes very unlikely that two runs would have the same order.  
( It was added for security reasons, which is an even better reasons to do this )

I just ran `perl -E 'say keys %{{1,1,2,1,3,1}}'` 6 times until I saw a repeat  
`213, 132, 231, 312, 321, 312`

**Comment by AlexDaniel** [comment]
Yes. Another related issue: [RT #130485](https://rt.perl.org/Ticket/Display.html?id=130485)
