### ISSUE TITLE
Add filter/sort ability to all html tables in docs

### ISSUE THREAD

**Issue by WildYorkies** [perl6/doc#1157]
For example, on the [All Types page](https://docs.perl6.org/type.html), I should be able to sort and filter the types by alphabetical order, by declarator, or by composite/basic/domain-specific (that column would need to be added).

There should be a jquery plugin for sort/filter of html tables.

**Comment by JJ** [comment]
Do we want/need this?

**Comment by AlexDaniel** [comment]
That wouldn't hurt, yes.

**Comment by JJ** [comment]
We would need to refactor a fair amount of code if we want to use something like [this library](https://github.com/christianbach/tablesorter). Including `Pod::To::HTML`

**Comment by zoffixznet** [comment]
> We would need to refactor a fair amount of code if we want to use something like this library. Including Pod::To::HTML

Wouldn't we just need to modify `htmlify.p6` to generate proper `<thead>` instead of simply boldening the first row? Looks like all the changes are limited to [Pod::Convenience::pod-table](https://github.com/perl6/doc/blob/c91b2de5e01b7abd2602de637d2b0bb5d1985a58/lib/Pod/Convenience.pm6#L97-L101) and any code that uses it, without a need to involve `Pod::To::HTML`
