### ISSUE TITLE
List::classify &as documentation missing.

### ISSUE THREAD

**Issue by bbkr** [perl6/doc#1162]
For lists it is possible to map classified value by using "as" option

```
say (1,2,3).classify( {  }, :as{  })
```

And while this is well documented in Hash::classify-list https://docs.perl6.org/routine/classify-list#:&as_value_modifier it should also be documented under List::classify here https://docs.perl6.org/routine/classify .

**Comment by zoffixznet** [comment]
`.classify` is actually a method on `Any` and `Supply`, not `List`, so that would need to be amended as well. It's probably best to document it in a way where we can just tell the reader to go read `.classify-list` docs, since `.classify` basically just reorders the args and forwards to `.classify-list`.

Raking [through Rakudo's source](https://github.com/rakudo/rakudo/blob/096bc17cd5805cc382ee3e5b21aba4945933aa05/src/core/Any.pm#L524-L541) I see it takes `:into` arg that is also undocumented. I'm unsure whether that's part of the spec or not
