### ISSUE TITLE
xt/examples-compilation.t doesn't tell you what failed

### ISSUE THREAD

**Issue by coke** [perl6/doc#1194]
A run just now shows: 

```
not ok 4 - Language/concurrency.p6 examples check isn't successful

# Failed test 'Language/concurrency.p6 examples check isn't successful'
# at xt/examples-compilation.t line 23
```

But some of the files have hundreds of lines.

The sanity check should be per example, and it should refer back to the line number in the original file.

**Comment by Altai-man** [comment]
This issue is good as a wishlist, but for now it works in different fashion.

If someone introduces a new example, he can run tests and look, is it working or not(and if not - you don't want to push it in the repo!). So, the changes author needs to review is a small subset of the actual file.

But yes, it will be a huge improvement to simplify your everyday work.

**Comment by coke** [comment]
Altai-man - if the test was clean and was part of t/, and run every time, sure. But as part of xt/ , it's very easy for it to get into a bad state, like it is now.

**Comment by Altai-man** [comment]
Indeed. I'm not sure by what criteria tests are selected to go into t/ or xt/. As for me, examples compilation test process is somewhat slow, that's why I placed it into xt/.

Anyway, closer to the core of the issue...

I can improve the test to grab the compiler output and print a line which was a cause of an error. It won't be as neat as original line number, because we lost it after extraction, but it will be much easier to just find appropriate string in a bad file.

On the other hand, I can parse pod6 files directly and check every example - and give proper line number to the user, but it will be some kind of already existing `extract-examples.pl6`. We can ask gfldex, who wrote it originally, what was his purpose in file extracting instead of such checking.

**Comment by coke** [comment]
t/ - things that should pass on every commit and can be considered to break the build.
xt/ - can fail without breaking the build, but should keep an eye on.

So, if someone's editor leaves some trailing white spaces, or they misspell a word, that's OK. I would actually argue that failing examples are bad and should break the build.

**Comment by Altai-man** [comment]
As I got it, tabs in files can break the build, but wrong examples are okay?

**Comment by coke** [comment]
As of today, yes.

**Comment by Altai-man** [comment]
Okay.
Anyway, I can take the job to check examples everyday(warning: not a solution).
I can update the test to show broken input, as I wrote in first variant too.
I can also discuss how it should work in general with gfldex and write some proper solution too.

This is my variants about how we can solve it.

**Comment by Altai-man** [comment]
Since I'm assigned, to print what exactly brought the compiler's wrath will be enough to close this?

**Comment by coke** [comment]
Ideally: each test should be a single example, not an entire file of examples. The diagnostic message should show the compilation error and the line number and filename of the original example in the file. (not an extracted version).

**Comment by coke** [comment]
FYI, made some changes here to compile only (not run) code, and to allow passing in a single file name to make testing changes faster.

**Comment by Altai-man** [comment]
Great! I'm short on time right now and will be able to work on this only on next weekend, so if this test is bothersome, you can temporary skip it until I make it better.

**Comment by coke** [comment]
Just tripped over this with trying to enable the haskell page - having all the examples going into a single file means that if you have two blocks that declare the same variable, it's considered a compilation failure - so this strengthens the idea of breaking out the example tests into a single chunk per.

**Comment by Altai-man** [comment]
There should be different lexical scopes as `{}` for every code tag in pod we parse, so the same variable definition in two different examples won't be the problem.
On the other hand, code like
```
my $a = 3;
my $a = 2;
```
won't be compiled.

Of course, it makes further reference to a variable defined in a different block invalid, but the code is not smart enough to see where there are free variables and where not.

**Comment by coke** [comment]
Getting the line number turned out to be very hard with the current pod tools, but saving the snippet so you can see the failed code itself was easy.

**Comment by Altai-man** [comment]
The test doesn't work.
When I messed a bit with a random example, the test anyway passed like normal, so I've began to investigate.
The culprit is https://github.com/perl6/doc/pull/1207/files#diff-9358e3af78070f12fd37561833e958dbR48.
When I removed map, so the line became
```
                'contents', $chunk.contents.join,
```
the test was correct. It seems that matching with `Mu` in `walk` always succeeds, so we just test empty strings.

For what reason did you add this map on walk in the first place? My obvious solution is to remove it, but I'm not sure, since I don't understand the purpose of this `walk` routine.

**Comment by coke** [comment]
Wasn't thinking about the placement when I added it; of course putting it first was a mistake. Fixing.

**Comment by Altai-man** [comment]
I already fixed it locally.

**Comment by Altai-man** [comment]
```
sub walk($_) {
    when Pod::FormattingCode { walk $_.contents}
    when $_.defined { $_ }
    default { "" }
}
```
This code seems correct, but it doesn't work for FormattingCode for some reason.

**Comment by Altai-man** [comment]
```
sub walk($_) {
    when Pod::FormattingCode { $_.contents.map({walk $_}).join }
    when $_.defined { $_ }
    default { "" }
}
```
^ is my solution. @coke, can I push it or you can come up with something better?

**Comment by coke** [comment]
I have something slightly better that deals with the occasionally Array type we get passed. one moment.

**Comment by coke** [comment]
Of course, the timings were so good before because we were running "False" every time. (new timing run is up to 1m9s)

**Comment by Altai-man** [comment]
I've tested 2a02ba23cb, seems fine now. This can be closed?
