### ISSUE TITLE
Perl 6 *will* solve the halting problem for you

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1202]
Well, no, but look!

[Documentation for .flat](https://docs.perl6.org/type/Pair#(Any)_method_flat):

> Please note that .flat will not solve the halting problem for you. If you flat an infinite list ``.flat`` may return that infinite list, eating all your RAM in the process.

OK, let's see.

Code:
```perl6
my @x = 1, 3 … *; say @x.flat
```

Result:
```
(...)
```

Turns out it works just fine with infinite things? Then why all these scary stories if there's no issue? When exactly does it reify stuff if it does ever?

**Comment by raiph** [comment]
"If you flat an infinite list .flat may return that infinite list, eating all your RAM in the process."

I presume your point is that "may" is vague. But it reflects the truth: Perl 6 tries to keep the list lazy but user code is in control.

Perhaps a concrete example of things going *wrong* would help. "If code asks for the quadrillionth element (`.flat[1e15]`) then Perl 6 will obediently try to fetch it -- and it's not going to succeed." But adding something like that doesn't feel like an improvement to me.

Perhaps a concrete example of things being done *right* would help. Your example is exactly that. `say` displays a `gist` of its arguments and `gist` is doing things right. A `gist` is a human friendly string that represents a given value; its handling of an infinite list is to return the five character string `(...)` rather than reify the list.

**Comment by toolforger** [comment]
On 18.02.2017 04:34, raiph wrote:
> "If you flat an infinite list .flat may return that infinite list,
> eating all your RAM in the process."
>
> I presume your point is that "may" is vague. But it reflects the truth:
> Perl 6 tries to keep the list lazy but user code is in control.
>
> Perhaps a concrete example of things going /wrong/ would help. "If code
> asks for the quadrillionth element (|.flat[1e15]|) then Perl 6 will
> obediently try to fetch it -- and it's not going to succeed." But adding
> something like that doesn't feel like an improvement to me.

For me, the first thing I was thinking was "but 1e15 - is that really 
more than computer memory can hold?"
Which detracted from the actual argument being made.

Maybe use "try to take the length of a lazy infinite list" as an 
example, Perl6 will then obediently construct and count every list element.

> Perhaps a concrete example of things being done /right/ would help.

I think both examples would be useful.
If people have seen an example from both side of the fence, it will be 
easier for them to determine where exactly the border is.

**Comment by zoffixznet** [comment]
> Then why all these scary stories if there's no issue?

As I recall there was a bug that in certain cases .is-lazy wasn't propagated by .flat. 

Fixed in https://github.com/perl6/doc/commit/6e1482811bba9ceec8f7a87fe85fbf2f613f8258
