### ISSUE TITLE
Clarify whether spawned processes get the current standard streams in docs

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1226]
The docs for [Proc](https://docs.perl6.org/type/Proc#method_shell) shell say

> $in, $out and $err are the three standard streams of the to-be-launched program, and default to "-", which means they inherit the stream from the parent process.

But, Brad Gilbert notes in my [StackOverflow question](http://stackoverflow.com/q/42505139/2766176) that Perl 6 won't pass on changes to `$*OUT`, etc to child processes. This seems wrong to me, but if that's the way it is, that's the way it is. If this is a design decision (much like the early issues with the Java in the 90s to standardize behavior for dissimilar devices), that should be emphasized as a major language decision.

I don't know what the answer is, but if Perl 6 will never pass on the current values of what it tells the user is standard output and so on, it shouldn't say that spawned processes "inherit the stream from the parent process".

**Comment by jnthn** [comment]
The docs are not arguably not wrong (though unarguably will lead to the same confusion you have). The STDOUT of the process lives in `PROCESS::<$OUT>`. Declaring a `my $*OUT = ...` is therefore not actually changing the STDOUT of the process as a whole (which there is, at present, not a way to do). Since handle inheritance is a process level thing, then that leads to the observed behavior.

Whether this is desirable is an entirely separate question. It's certainly inconsistent with `%*ENV` and `$*CWD`, which we do make use of when we spawn a new process. To be clear, the reason we use dynamic variables here is because the (OS-level) `chdir` and `setenv` are dangerous in a multi-threaded application; the first we expose as `PROCESS::<&chdir>` if you should really wish to change the process' working directory, and the latter you'll have to get at with `NativeCall`. Otherwise, programs never really change the working directory or environment, we just reflect the changes when doing things like opening files and spawning processes.

That we reflect changes to `$*CWD` and `%*ENV` when spawning a process suggests to me that we should do the same with `$*OUT` and `$*ERR`. We can't do handle inheritance at the file descriptor level in the general case, since `$*OUT` can be bound to pretty much anything (this is how I/O capturing modules are done). But that's not really an obstacle; we'd just read from the process and write to said handles, if we spot they aren't the same as the process-level ones. If others agree, we can RT this and I can look at implementing it.

**Comment by coke** [comment]
@briandfoy  - can you fix the title? It seems to be missing a word.

**Comment by AlexDaniel** [comment]
Can somebody turn this into a TODO list of things to do? Otherwise this ticket looks scary.

**Comment by JJ** [comment]
Is this about clarification of who gets the standard streams? If so, it's just changing a sentence. This one:

> it shouldn't say that spawned processes "inherit the stream from the parent process".

Tells us what to do, right?
