### ISSUE TITLE
sprintf '<%#.5o>' is wrong

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1248]
The [`sprintf '<%#.5o>',` examples](https://github.com/perl6/doc/blob/db236af9f32404ed9921ed5c3288941ecbcee6eb/doc/Type/Str.pod6#L543-L545) are wrong [[link]](https://github.com/perl6/doc/blob/db236af9f32404ed9921ed5c3288941ecbcee6eb/doc/Type/Str.pod6#L543-L545)

1) they issue a warning because in Perl 6 the leading-zero does not indicate an octal number
2) the output shown is incorrect, because the real output is in octal:
```
<Zoffix> m: printf '<%#.5o>', 12345;
<camelia> rakudo-moar b19df9: OUTPUT: «<030071>»
```

I'm not 100% sure whether that output is correct though. It's not a Perl 6 octal number, but is that by design because all `sprintf`s in the world probably do it that way?

Don't have the time to check that at the moment, but maybe someone else has...

**Comment by dmaestro** [comment]
There is also a question of how the `#` modifier _should_ work - the doc says `the precision is incremented if it's necessary for the leading "0"` (notice "if"), but it seems to be _always_ incrementing the precision.

    [13:12] <camelia> rakudo-moar c95c4a: 
    m: say sprintf "%.5o", 0o123
    OUTPUT: «00123␤»
    m: say sprintf "%#.5o", 0o123
    OUTPUT: «000123␤»    # extra precision not needed!
    m: say sprintf "%.5o", 0o12345
    OUTPUT: «12345␤»
    m: say sprintf "%#.5o", 0o12345
    OUTPUT: «012345␤»
    m: say sprintf "%.5o", 0o1234
    OUTPUT: «01234␤»
    m: say sprintf "%#.5o", 0o1234
    OUTPUT: «001234␤»    # extra precision not needed!

**Comment by dmaestro** [comment]
I see nothing in `roast` to resolve the question.

**Comment by AlexDaniel** [comment]
https://github.com/perl6/doc/commit/d1d9b5cc9ae17daf19b368e7e4452390fec5a923

**Comment by AlexDaniel** [comment]
Why does it even use this leading zero notation for octal numbers? Why not ``0o00012``? I do understand that this is how it was done in the past, but why would we want to preserve this?

**Comment by JJ** [comment]
Let me see if I understand this correctly. Is this an error somewhere in Rakudo, or an error in the documentation?
At least that last one is correct:
```
rakudo-moar db8b218f6: OUTPUT: «Potential difficulties:␤    Leading 0 has no meaning. If you meant to create an octal number, use    '0o' prefix; like, '0o12'. If you meant to create a string, please add quotation marks.␤    at <tmp>:1␤    ------> sprintf      '<%#.5o>', 012⏏<…»   
```

**Comment by dmaestro** [comment]
The documentation has been fixed / improved several times since this ticket was open. The [current master](https://github.com/perl6/doc/blob/0a4653da7b9a1d9028e9d6cda722c18e1267381b/doc/Type/Str.pod6#L491) seems to be in good shape.
Part 1 of the original question has been fixed by using '0o12345' instead of '012345' for the literal parameter to the function.
Part 2 seems to have been settled on keeping POSIX behavior of the function - even though the output (Str) does not round-trip back as a Perl 6 literal. Considering that the common, historical use of the function is for human-readable output formatting, I believe this is correct.

Perhaps a disclaimer should be added to the doc that this function, though useful to many, is more of a historical unix-ism, and not fully in the spirit of Perl 6. The name itself may be enough of a hint, though, a non-POSIX, Perl6-style formatter should certainly have a different name!

**Comment by JJ** [comment]
I've added a note, but I didn't want to be too negative about that. Considering that part of the DSL is NYI, I didn't want people to be too discouraged to use it. Besides, it's intended to return a C<Str>, it's not a real base conversion function (we do have better routines for that)
