### ISSUE TITLE
Mistake in example

### ISSUE THREAD

**Issue by MARTIMM** [perl6/doc#1252]
Found a mistake in the doc (or a misfuncton of my brain) on page http://docs.perl6.org/language/quoting at section 'Word quoting: qw'.
The first example uses the .words method at the end which I think should not be there for eqv to work.

Regards,
Marcel

**Comment by AlexDaniel** [comment]
Thanks for bringing up the issue!

Did you mistake ``eqv`` with ``eq``? ``.words`` is there for a good reason, that's not a problem. You get iterables on both sides (lists or seqs), and that's what you're trying to compare. It's not a string comparison.

That being said, the example is no longer working.
```
¦«2015.09,2015.10,2015.11,2015.12,2016.01.1,2016.02,2016.03,
  2016.04,2016.05,2016.06,2016.07.1,2016.08.1,2016.09,2016.10,
  2016.11,2016.12,2017.01,2017.02»: True
¦«2017.03,HEAD(fbe7ace)»: False
```

Bisect:
```
<AlexDaniel> bisect: say qw|! @ # $ % ^ & * \| < > | eqv '! @ # $ % ^ & * | < >'.words
```
> \<bisectable6\> AlexDaniel, Bisecting by output (old=2015.12 new=fbe7ace) because on both starting points the exit code is 0
> \<bisectable6\> AlexDaniel, bisect log: https://gist.github.com/43c1626229a204c085acb06d3573118f
> \<bisectable6\> AlexDaniel, (2017-03-01) https://github.com/rakudo/rakudo/commit/f9eb811dd20074e902debddcb2de426d700335de

So the change seems to be intentional, that's good. But we have to fix the example you mentioned.
