### ISSUE TITLE
Misspell in Angle brackets？

### ISSUE THREAD

**Issue by ybj2004** [perl6/doc#1285]
https://docs.perl6.org/perl6.xhtml  
Angle brackets <  > have displayed as &lt and &gt

**Comment by zoffixznet** [comment]
Thanks. Fixed the `&lt` thing, but now noticing more code chunks double-escaped, like triple-escaped markup in code example in `29.2.7 Object Construction` section.

The Pod::To::HTML thing needs a saner rewrite to fix all the issues.

**Comment by JJ** [comment]
Isn't this one rendered by Pod::To::Bigpage? Also related: #1825

**Comment by zoffixznet** [comment]
Yeah, the rendering issues are now fixed. Unrelated to report in OP, there're a [bunch of markup errors](https://validator.w3.org/nu/?doc=https%3A%2F%2Fdocs.perl6.org%2Fperl6.html) because of illegal IDs that start with a digit. Don't know if there's anything else, as the validation ends with "too many messages".

**Comment by JJ** [comment]
It's again these fake URLs due to HTML errors. I thought I had fixed some
of them...

**Comment by W4anD0eR96** [comment]
It should be fixed by perl6/perl6-pod-to-bigpage@9fe402be403b64152bee04

I test it locally and do not know why it is not applied when generates.

**Comment by zoffixznet** [comment]
> I test it locally and do not know why it is not applied when generates.

Because module updates need to be installed on the server by the admins manually.

**Comment by W4anD0eR96** [comment]
Ok, then it has been fixed.
