### ISSUE TITLE
Using whitespace between ... and ^ is a possible trap

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1291]
Code:
```
my $x = 5; say 0 ... ^$x
```
Result:
```
(0 1 2 3 4)
```

Code:
```
my $x = -5; say 0 ... ^$x
```
```
Cannot get sequence endpoint from an empty list (use * or :!elems instead?)
  in block <unit> at -e line 1
```

Code:
```
my $x = -5; say 0...^$x
```
Result:
```
(0 -1 -2 -3 -4)
```

**Comment by zoffixznet** [comment]
"taking" this Issue as I'm actually hoping to make Rakudo detect this accidental use rather than rely on users to learn of this from the docs. Or rather, detecting it is easy, but trying to think of a good suggestion to offer in the error in case the user *did* in fact mean to use a Range as RHS list.

It's in my todo list, though I'm a bit booked for the next couple of weeks.

**Comment by AlexDaniel** [comment]
@zoffixznet ping?

**Comment by zoffixznet** [comment]
> detect this accidental use [...] Or rather, detecting it is easy

Sorry, last year's Zoffix, but `&infix:<...^>` is a valid op, you n00b 😆

**Comment by AlexDaniel** [comment]
Cool. Thanks to you both!
