### ISSUE TITLE
Doubled words

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1338]
I wonder if there is any way to automate this, or if somebody can run a set of commands from time to time to search for new problem.

For example, I just did this:
```
grep -Pr '(\s+\w+)\1\s' *
```
Stupid, I know, but here is what I found:

* [``is made, so the returned parent parent is physical and not the logical parent of``](https://github.com/perl6/doc/blob/68be3615a6b6ab8a0f6789845d3a42d818491695/doc/Type/IO/Path.pod6#L438)
* [``This could be be used as a primitive kind of alarm clock. For instance, say``](https://github.com/perl6/doc/blob/68be3615a6b6ab8a0f6789845d3a42d818491695/doc/Type/Date.pod6#L293)
* [``triangular list of of lists, you can use a "triangular comma":``](https://github.com/perl6/doc/blob/68be3615a6b6ab8a0f6789845d3a42d818491695/doc/Type/List.pod6#L825)

I am pretty sure you can find more problems with a better regex.

**Comment by JJ** [comment]
Can't that be added to the t/ dir as a test? There is already a tabs test,
for instance.

**Comment by AlexDaniel** [comment]
Not really because of all false positives :(

Well, unless you can find a way to eliminate almost all false positives.

**Comment by JJ** [comment]
False positives seem to happen mainly in code...

**Comment by coke** [comment]
Test added.

* Skips implicit and explicit code blocks,
* Reports line number and word.
* While it works line by line, it keeps track of the last word on the previous line.
* Unless it was a POD directive, so that one word headers who are followed with a sentence that starts with the same word aren't counted.
* Some very common dupes are allowed (long long and method method)

Found the 3 cases mentioned here plus a few others.

**Comment by AlexDaniel** [comment]
@coke you are awesome.
