### ISSUE TITLE
A "return to top" link would be nice

### ISSUE THREAD

**Issue by zostay** [perl6/doc#1339]
On some of the longer docs, it's a pain to scroll back to the top to start a new search. In theory, I know I can click "Home" on my keyboard and do that any time, but in actuality, I always forget. It would be nice if there were a link fixed to the side when you scroll down that will scroll you quickly back up to the top. This is purely a convenience.

**Comment by AlexDaniel** [comment]
👎
As already mentioned, you can use Home button. And if that's too hard you can always install one of [one of these addons](https://addons.mozilla.org/en-us/firefox/addon/scroll-to-top/).

**Comment by zoffixznet** [comment]
> to start a new search

You can start it by pressing Esc.

Ctrl+Home is scrolls to top in most things with text, so forgetting about it is a poor excuse for adding more clutter into already busy page IMO.

The mentioned addon is a good remedy for those who forget... On my mobile browser I get a fast scroll button show up the second I shift the page up, so feels like this is a problem with the tools rather than the website IMO.
