### ISSUE TITLE
mention file handles no auto close in Traps to avoid

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#1365]

**Comment by zoffixznet** [comment]
As mentioned on IRC. It's not a trap. It's basic operation of Perl 6 IO.

The behaviour is already documented in [IO::Handle.open](https://docs.perl6.org/type/IO::Handle#method_open), [IO::Handle.close](https://docs.perl6.org/type/IO::Handle#routine_close), [appending content section of IO guide](https://docs.perl6.org/language/io-guide#Appending_content), and mentioned in [IO::CatHandle.close](https://docs.perl6.org/type/IO::CatHandle#method_close).

If someone still haven't learned about the fact by then, they're not reading the documentation, and adding it to Traps is wasted effort and pointless extra noise.

**Comment by AlexDaniel** [comment]
Well, just because something is a “basic operation” does not mean that a trap turns into a non-trap.

It is very good that we have this stuff documented. Very good. But a mention on traps page is not going to hurt.

Therefore, I think we should still list it, and provide links that you mentioned.

**Comment by zoffixznet** [comment]
> Well, just because something is a “basic operation” does not mean that a trap turns into a non-trap.

Yes, it does. What else will you put into traps? Lists turning into hashes on assignment? Mutating objects from multiple threads causing races? A single user makes a single mistake and you rush to put it into Traps.

Let's put everything into traps, why not! Hell, if the user didn't read it in the four different places that actually talk about features they're attempting to use, then they'll definitely read it in the Traps page, amirite?

**Comment by ronaldxs** [comment]
People coming from Perl 5 may expect object destruction when leaving a block/scope.  The IO docs help with close and experienced Perl 6 programmers will know that p6 memory management will handle scope and destructors differently.  I think there is a need to document the difference from p5 in either or both of the P6 OO docs and the 5to6 docs.

**Comment by tbrowder** [comment]
On Tue, Jun 6, 2017 at 19:02 Ronald Schmidt <notifications@github.com>
wrote:

> People coming from Perl 5 may expect object destruction when leaving a
> block/scope.
>

As the OP, 20+ years of C, C++, and Perl have ingrained in me to not worry
about open file handles at scope end.  I do remember reading early on about
the difference in Perl 6, but forgot about it until the :close and spurt
issue arose on IRC.

Putting aside mentioning in Traps or not, how about starting a list of Perl
lint items, such as unclosed file handles, open or unmatched pod
=begin/=end blocks, etc.?

**Comment by AlexDaniel** [comment]
@zoffixznet Hm. Have you ever seen [BashPitfalls](http://mywiki.wooledge.org/BashPitfalls)? Most things there talk about basic bash functionality, and indeed most of it is already documented elsewhere. However, people still do mistakes. And that page is extremely helpful.

I want our traps page to be exactly like BashPitfalls. If something is already explained elsewhere, great! Just add a link to it.

**Comment by jnthn** [comment]
I agree we need to prioritize, and we shouldn't be including every single thing that somebody managed to trip over. If it gets too long, it will lose its purpose. So some hesitation before adding things is right.

IMO, this case does warrant a mention. While there will be many developers for whom it is not in the slightest bit surprising (those coming from Java or C# for example), for plenty of others who have relied on reference counting timely destruction semantics it will be - of note, those coming from Perl 5. And the consequences of getting it wrong range up to "program runs out of file descriptors and stops working". Thankfully, the `LEAVE` phaser makes many cases easy to get right, and lets the `close` call be placed right next to the `open` call, so the reader can immediately stop worrying "does this code remember to close it later".

Finally, I'll note that just because something is a trap people might walk into doesn't mean it's a problem with the language design. In this particular case, if we'd picked a different kind of memory management, we'd just have had a different trap to write about instead. Often there's only trade-offs, and this is one such case.

**Comment by AlexDaniel** [comment]
If it gets too long, we will refactor. For example, we can have two pages: traps-for-beginners and advanced-traps. The page getting too long is not something we should worry about right now.

**Comment by coke** [comment]
I would consider breaking it up into sections by language (or at least tagging the language) since the goal is to warn people coming from other languages.

**Comment by AlexDaniel** [comment]
Perfect.
