### ISSUE TITLE
command line "p6doc -f push" doesn't work

### ISSUE THREAD

**Issue by stmuk** [perl6/doc#138]
% p6doc
What documentation do you want to read?
Examples: p6doc Type::Str
          p6doc Type::Str.split

You can also look up specific method/routine defintions:
          p6doc -f push

%  p6doc -f push
We have multiple matches for 'push'

        Array.push .push .push .push .push .push
        Hash.push .push .push .push .push .push

%  p6doc -f Array.push
===SORRY!===
Cannot invoke this object (REPR: Uninstantiable)

**Comment by ab5tract** [comment]
Yes. As I said before, the GLR breaks things. I was certain that I had
pushed a patch for this already. Let me check locally and push, if it is
there.

**Comment by ab5tract** [comment]
Apparently this was fixed on a different box.

Anyway, the repetitive .push was an easy fix (GLR making life easier).

The REPR: Uninstantiable is a different story. These seems to be an issue at the index.dat level.

**Comment by ab5tract** [comment]
Apparently I fixed it on a different machine. Will check. The fix for the repetitive .push in the output is an easy fix.

The REPR: Uninstantiable is a different bug. I decided to shelve my attempt to fix it, since we were already discussing using a `p6doc-server` kind of thing which could do something smarter/different WRT to the compiled pod structure.

**Comment by stmuk** [comment]
fixed in https://github.com/perl6/doc/commit/cbd940329c
