### ISSUE TITLE
val() doesn't show up in search results on website

### ISSUE THREAD

**Issue by briandfoy** [perl6/doc#1404]
I thought I'd just have to go into `Str.pod6` to add an indexing element, but nothing else in there has an `X<>`. I didn't see any instructions for this sort of problem. Other routines show up in the index, though. I tried running the `htmlify` target but got several screens of npm errors.

I've encountered this sort of thing with other things I can't remember but I'd always diverted myself to the type page.

**Comment by AlexDaniel** [comment]
Is this some sort of fuzzy search issue? If you type “val” it doesn't find ``val``, but if you type “vla” it does.

Ping @coke.

**Comment by coke** [comment]
FYI, npm is called because of the highlighting code; you can skip that by passing --no-highlight to htmlify.

Found the issue, it's something that happens with sift4() when using the maxDistance parameter; we were passing in 3 for 'val' vs. 'val', and it returned a distance of 3. Setting it to 0 returned the correct distance of 0.

So, stopped trying to be clever with maxDistance, just passed in 0, fixes the issue.

**Comment by coke** [comment]
Ok, two things going on here; one, our use of maxDistance in the sift4 algorithm caused it to return wonky results comparing 'val' to 'val'  - we somehow got a distance of 3, instead of 0; lif we avoid that parameter entirely, we get the expected 0 for identical strings.

Next thing is that we limit the results to the first 50 that come back; because we don't sort results (and especially don't put exact matches first),  this then causes it to get dropped.

Looking at why we get so many hits, I realized that our maxOffset calc was fubar. changed the max offset to Math.min(4, len-2), which restricts it MUCH better for lower length search teams.
