### ISSUE TITLE
index **@ and **%

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1416]
One who is new to the language might not know that it's called a slurpy. Also, there are anon slurpies.

**Comment by skycafemix** [comment]
Yes, this would be helpful to new users. I myself noticed you cannot look up **@ in the online docs. 

Relevant links:
(1)  https://docs.perl6.org/syntax/*@#(Signature)_parameter_*@
(2)  https://docs.perl6.org/language/functions#Slurpy_Conventions
(3)  https://docs.perl6.org/type/Signature#Single_Argument_Rule_Slurpy
The topic is covered on slide 72 ("Non-flattening slurpy positional") of the file included in Rakudo docs folder called 2015-spw-perl6-course.pdf

Recommend add a link from #1 above to #3 so that all three of the above pages are linked together.

Also recommend a search results suggestion could be added for "** (Single Argument Rule Slurpy)" because:
- Type + into the search box you get "+ (Single Argument Rule Slurpy)" which is great
- Type ** and it gives exponentiation and coercion but no slurpy. It does show *@ though.

Incidentally, on the page https://docs.perl6.org/syntax/*@ the last line seems to be incomplete. 
- It says "as described below" with nothing below it
- It includes a link to the following url anchor which does not exist: https://docs.perl6.org/syntax/*@#Parameter_Traits_and_Modifiers

Sorry I am as yet too new to the language to feel comfortable making a pull request!

**Comment by JJ** [comment]
I'm closing this temptatively. I haven't found references to **% either in the Synopse or in roast. So I'm not sure it's a thing, and come to think of it, how do you flatten a hash? Although the syntax is correct, it doesn't really do a thing. In that sense, it might be a bug, but waiting for some real examples of use and some proof of existence, I'm closing it.
