### ISSUE TITLE
bad "handles" example in doc/Language/subscripts.pod6

### ISSUE THREAD

**Issue by coke** [perl6/doc#1438]
This sample code:

```
    class HTTP::Header does Associative is Iterable {
        subset StrOrArrayOfStr where Str | ( Array & {.all ~~ Str} );

        has %!fields of StrOrArrayOfStr
                     handles <AT-KEY EXISTS-KEY DELETE-KEY push
                              iterator list kv keys values>;

        method Str { #`[not shown, for brevity] }
    }
```
Is presented as an example of handles, but if you run it, you get:

```
===SORRY!=== Error while compiling -
Class HTTP::Header can't pun role Iterable because it has required methods: iterator. Did you mean to use "does" instead?
at -:1
```
and if you fix that, you get:

```
Method 'iterator' must be implemented by HTTP::Header because it is required by roles: Iterable.
```

So this sample code isn't doing what it claims to.

**Comment by zoffixznet** [comment]
The first one is a proper error, it sould be `does` instead of `is` (fixed in https://github.com/perl6/doc/commit/492896feb7092c51a80ba2260e48b0b9e791bf82)

> Method 'iterator' must be implemented by HTTP::Header because it is required by roles: Iterable.

I'd call that a rakudo bug; it fails to see the `handles` is providing `iterator` method. This is [already reported](https://rt.perl.org/Public/Bug/Display.html?id=131676#ticket-history) as a more direct bug, but I mentioned this case as well.

So... this ticket looks to be fixed to me, now.

**Comment by coke** [comment]
Ideally, we'd reference the RT in the user-visible code, and remove the skip once the bug is fixed.

**Comment by JJ** [comment]
Checking that the RT bug is still open.

**Comment by JJ** [comment]
There's a patch submitted: rakudo/rakudo#1170, but it has not been accepted yet.
