### ISSUE TITLE
better examples for term

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1445]
The documentation of [term:<>](https://docs.perl6.org/language/syntax#Term_term:%3C%3E) is fairly thin. It doesn't really explain what the compiler is doing with a user defined term. And the example doesn't help to illustrate either. As follows at least a better example.

`sub f(|c){ dd c }; constant term:<GMT> = :0timezone; f GMT`

**Comment by gfldex** [comment]
`sub f(:$timezone){ say $timezone }; constant term:<GMT> = timezone => 0; f |GMT`

This example is actually correct and requires less prior knowledge.

**Comment by AlexDaniel** [comment]
Your example does not defy rules of normal identifiers (which is something the current example wants to show).

For example:
```perl6
sub f(:$timezone){ say $timezone }; constant \GMT = timezone => 0; f |GMT
```
So let's keep 👍 character there, or feel free to change it to something else (with something that is not in a-z range).

**Comment by b2gills** [comment]
That isn't a better example as it also works if you just declare it as a normal constant.

About the only difference I can see is what the error message says if you put parens after it, as if it was a subroutine. (It is also implementation specific.)

    sub f(|c){ dd c }; constant GMT = :0timezone; f GMT()
    ===SORRY!=== Error while compiling:
    Variable '&GMT' is not declared
    ------> d c }; my constant GMT = :0timezone; f ⏏GMT()}



    sub f(|c){ dd c }; constant term:<GMT> = :0timezone; f GMT()
    ===SORRY!=== Error while compiling:
    Undeclared name:
        GMT used at line 1

A better example that shows a `term:<…>` constant, is one that couldn't otherwise be a constant because it doesn't follow the rules for being an identifier.

    > constant term:<␤> = "\n"; say ␤.perl
    "\n"



    > constant ␤ = "\n"; say ␤.perl
    ===SORRY!=== Error while compiling:
    Missing initializer on constant declaration
    ------> constant⏏ ␤ = "\n"; say ␤.perl

---

It might be worth mentioning that a `term:<…>` seems to hide a normal constant, but this may be implementation specific.

    > constant term:<foo> = 1; constant foo = 0; say foo
    1



    > constant foo = 0; constant term:<foo> = 1; say foo
    1

----

Showing a `term:<…>` subroutine on the other hand, shows you that can create something that textually seems like a constant, but is not actually a constant.

    > sub term:<foo> { $++ }; say  (foo, foo, foo, foo);
    (0 1 2 3)



    > sub term:<foo> { $++ }; say  foo();
    ===SORRY!=== Error while compiling:
    Undeclared routine:
        foo used at line 1

This could be used to read in a config file at runtime rather than at compile time, but otherwise use it as if it were a constant.

**Comment by smls** [comment]
> Showing a term:<…> subroutine on the other hand, shows you that can create something that textually seems like a constant, but is not actually a constant.
> 
>     > sub term:<foo> { $++ }; say  (foo, foo, foo, foo);
>     (0 1 2 3)

That example would work the same if `foo` was defined as a normal `sub`.

Instead, I think it should show a case where `foo` it is followed by whitespace, to demonstrate that it does **not** parse the rest of the statement as its argument list like a `sub` would. e.g.:

``` Perl 6
sub term:<counter> { $++ };  say  counter ~ "," ~ counter;  # 0,1
```

**Comment by b2gills** [comment]
> That example would work the same if foo was defined as a normal sub.

Which is exactly why I showed in the very next example that trying to call it with parens is a compilation error.  
I just didn't spend the time and effort to think about all the other syntactic ramifications.

I agree that showing all of the differences between a normal sub and a term sub is beneficial.

**Comment by JJ** [comment]
Probably not the right place, but maybe a link to this way of redefining term should be added to the `functions` page. Just a link would do, probably. After @gfldex article on golfing, I tried to look it up there, to no avail.
