### ISSUE TITLE
Discuss performance benefits of native types

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1534]
From https://github.com/perl6/doc/issues/372#issuecomment-326795282:
> Native int, num and so on can be used to speed up thing, like shaped Array. They are not only useful with NC

**Comment by jnthn** [comment]
Not only speed things up, but natively typed arrays can be a giant memory saving also where applicable.

**Comment by AlexDaniel** [comment]
Where could this go? [nativecall](https://docs.perl6.org/language/nativecall) page is not exactly the right place. And as native types go, we only have [int](https://docs.perl6.org/type/nativeInt) documented. After https://github.com/perl6/doc/issues/372 all native types point to nativecall page but again that's not entirely right.

**Comment by jnthn** [comment]
The [int documentation](https://docs.perl6.org/type/nativeInt) is somewhat unfortunate in that it lists a load of methods you can call on a "native int". This not quite true, as you can't call a method, or indeed do anything object-y, on a native type. Calls to such methods will box the native integer into an `Int` and the method will be called on that (one can observe this by trying `(my int $x = 42).WHAT` and observing it says `Int`, not `int` - the reason is that the `int` was boxed into `Int` to have something to ask for the type object of).

Perhaps making the native int documentation describe what a native integer is, the sized variants, and its boxing behavior (with a link to `Int` documentation) would be more useful?

**Comment by JJ** [comment]
I can think either of a new `performance issues` page or the already existing traps page.

**Comment by AlexDaniel** [comment]
@JJ no-no, I think this should go directly to the same place where native types are discussed. Unfortunately, I don't know about a page like this.

To clarify, a person searching for “int” should be able to eventually land on a page which discusses packed native arrays and stuff like that. And there we can say why the user may want to do that at all (e.g. for *performance* reasons).

**Comment by AlexDaniel** [comment]
Currently searching for `int` gives https://docs.perl6.org/type/nativeInt which says “TODO”. Not good at all :(

There's also https://docs.perl6.org/language/nativecall but that's a different topic IMO.

**Comment by zoffixznet** [comment]
FWIW the CaR grant branch that'll be merged after next release (2018-05-19) adds a ["Numerics" language page](https://github.com/perl6/doc/blob/car-grant-midrat/doc/Language/numerics.pod6) that does mention native types as well as their performance benefits, including the case where they're lost because code does a lot of boxing.
