### ISSUE TITLE
explain public attributes in /typesystem

### ISSUE THREAD

**Issue by gfldex** [perl6/doc#1572]
There seems to be confusion https://colabti.org/irclogger/irclogger_log/perl6?date=2017-09-22#l268

**Comment by JJ** [comment]
I'm trying to wrap my head around this issue, and I can't say I have managed to do so.
First, from the conversation it's not clear whether this applies to attributes or to variables in general, since "everything is a container", and [@moritz says "for all variables"](https://colabti.org/irclogger/irclogger_log/perl6?date=2017-09-22#l285)
Second, not clear also what needs to be explained. If we stick to the [question](https://colabti.org/irclogger/irclogger_log/perl6?date=2017-09-22#l270):
> is this an lvalue method call or a variable access
I guess that would be easy by using @moritz answer. But in that case I'm not sure this would apply to typesystem, since we are not really talking about how types work, rignt?

**Comment by JJ** [comment]
Unless I'm missing something, this does not work:

```
class Foo { has $.bar };
(Foo.new.bar = "Hi").say  # Cannot modify an immutable 'Any' type object␤ 
```

So I probably need a bit of more context. @moritz ? @fluca1978 ?
