### ISSUE TITLE
xt/aspell.t failure: Connor

### ISSUE THREAD

**Issue by coke** [perl6/doc#1620]
The name "Connor" was recently added to one of the docs, failing the spelling test.

Need to add "connor" to xt/words.pws (and keep it sorted)

**Comment by jstuder-gh** [comment]
That was my addition. I wasn't aware of the spelling issue. So string literals in examples are subject to spelling checks? I will keep that in mind for the future.

I won't be able to make the changes until tonight but at that time I will make the change you outline above. Thanks.

**Comment by jstuder-gh** [comment]
I will also be more cognizant of running the tests in the future. I neglected the tests and they would have pointed out this issue immediately. Since the HTML docs compiled I figured everything was good. I apologize for that. I will definitely run the tests for this repo more proactively in the future.
