### ISSUE TITLE
Useless  "Documentation for " in some page titles.

### ISSUE THREAD

**Issue by rafaelschipiura** [perl6/doc#1623]
From splitting #1212 

 remove the "Documentation for " string that's prepended to the title of some pages (it seems useless; why was it added?) to make more room ;

**Comment by coke** [comment]
Can you provide an example of a page that contains this?

**Comment by rafaelschipiura** [comment]
@AlexDaniel Can you provide examples?

**Comment by raiph** [comment]
Some (all?) of the routine pages, eg https://docs.perl6.org/routine/Date

**Comment by AlexDaniel** [comment]
So it should simply say “Method Date”, right?

LHF then, just change these:
https://github.com/perl6/doc/blob/c46c96b77b3f4e226ba7ec258f8f9a548cf10691/htmlify.p6#L901-L902
https://github.com/perl6/doc/blob/c46c96b77b3f4e226ba7ec258f8f9a548cf10691/htmlify.p6#L929

**Comment by AlexDaniel** [comment]
@W4anD0eR96 I think it should be “Method Date” and not “method Date”. I guess a call to ``.tc`` won't hurt?

**Comment by W4anD0eR96** [comment]
@AlexDaniel , should it?

I will agree with that about "Method Date". it requires change "method" to "Method"

https://github.com/perl6/doc/blob/9659f324ebe600436a2ae098284d5e2da9861452/htmlify.p6#L929



However, "infix" should not be "Infix", I think.

https://github.com/perl6/doc/blob/9659f324ebe600436a2ae098284d5e2da9861452/htmlify.p6#L901

**Comment by W4anD0eR96** [comment]
@AlexDaniel , now my opinion is opposite of yours.

1. In /type/*, like https://docs.perl6.org/type/AST, we use `method` and `class`

2. change code at line 929 will not convert all `method` to `Method`

For details, it works on https://docs.perl6.org/routine/(cont).%E2%88%8B.html,
but fails on https://docs.perl6.org/routine/old.

That's because the logic used to build there two sites are different. If we insist convert all `method` to `Method`(while keep `infix` as`infix`), then we should test if `$subkind eq 'method'`, that's quite dirty

**Comment by AlexDaniel** [comment]
@W4anD0eR96 OK. Then let's keep it lowercase and if somebody else complains, we'll do something about it. Until then, this can be closed! :)

Thanks!
