### ISSUE TITLE
Lock.lock/.unlock.... what exactly do they do?

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1626]
[The docs for `Lock.lock` and `Lock.unlock`](https://docs.perl6.org/type/Lock#method_lock) just say the methods "acquire" and "release" the lock... but what exactly does that mean? What happens? When would a user want to do that? Code examples?

**Comment by jnthn** [comment]
Things to make sure are mentioned:

* This construct provides a low-level, OS-backed, lock (on most platforms, it is a pthreads mutex, for example).
* The lock is reentrant, meaning that if you acquire it while already holding it then it just bumps a recursion count.
* Trying to acquire the lock when something else is holding it will really block a thread. If you block a thread pool thread with this construct, it won't be able to work on anything else in the meantime. Further, an `await` while holding a lock will not function in a non-blocking manner (as a threadpool `await` normally would in 6.d).
* Use `protect` instead of an explicit `lock`/`unlock`. That makes sure that the lock is always released. If you forget to `unlock` then you'll "lose" the lock and nothing will ever be able to acquire it again, probably resulting in the program deadlocking. If you really want to do the `unlock` yourself, the safest way is in a `LEAVE` phaser.
