### ISSUE TITLE
Regexes' bugs on LTM, custom <ws>

### ISSUE THREAD

**Issue by W4anD0eR96** [perl6/doc#1638]
`grammar { rule TOP { | 'if' 'else' | 'if' }}.parse("if else").say; # OUTPUT «｢if else｣␤»`
works well, but:
`grammar { rule TOP { | 'if' | 'if' 'else'  }}.parse("if else").say; # OUTPUT «Nil␤»`

some attempt to fix it:
`grammar { token ws { \s+ }; token zs { \s+ }; token TOP {['if' | 'if' <.zs> 'else'] $} }.parse("if else").say # OUTPUT: «｢if else｣␤»`
but:
`grammar { token ws { \s+ }; token zs { \s+ }; token TOP {['if' | 'if' <.ws> 'else'] $} }.parse("if else").say # OUTPUT: «Nil␤»`

so, first it seems LTM fails on some cases, and second, custom \<ws\> confuse sometime

**Comment by W4anD0eR96** [comment]
@moritz @zoffixznet

**Comment by smls** [comment]
Not a bug &ndash; just another example for why we need to

&nbsp;&nbsp;&nbsp; [#1550 **Explain LTM (longest token matching) in regexes**](https://github.com/perl6/doc/issues/1550)

:)

---
## Explanation of your examples 1 and 2

LTM only considers the **declarative prefix** of each branch, and the builtin `<ws>` is intentionally<sup>1</sup> defined in such a way that it counts as non-declarative. That's why it's called "longest **token** matching" - it generally branches based on the next "token" in the colloquial sense, i.e. it essentially does the job of a lexer.

In your first two examples, _both_ branches have the same declarative prefix `'if'`. So it chooses the first branch (based on the final tie-breaker "the earlier alternative [...] wins"<sup>2</sup>).

Because `rule` has `:ratchet` mode enabled by default, it sticks with the first branch even if that causes the match to fail, and doesn't backtrack to try the other branch.

If you want it to match, you have several options, for example:

1. Enable backtracking (using `regex` or `:!ratchet`).
1. Re-define `<ws>` using only declarative primitives, so that it will be considered declarative.
1. Avoid calling `<ws>`, as in `'if'\s+'else'`

## Explanation of your examples 3 and 4

`<ws>` matches on every whitespace sequence between regex atoms, even if those atoms are themselves calls to `<ws>`. So in your example, the `<ws>` rule is called three times in a row:

    'if' <.ws> 'else'
        ||    |
        12    3

Since you've defined your `<ws>` as `\s+` ("eagerly match **one or more** whitespace chars"), the first of those three calls already matches all the available whitespace at that position and leaves none for the other two calls. The solution is to just write:

    'if' 'else'

The whole point of using `rule`+`<ws>` is, after all, to _not_ have to explicitly write out those calls.

---
<sup>1) See the bullet-point list at [S05#Longest-token_matching](http://design.perl6.org/S05.html#Longest-token_matching).</sup>
<sup>2) See the bullet-point list at [S05#Overview](http://design.perl6.org/S05.html#Overview).</sup>

**Comment by W4anD0eR96** [comment]
@smls thank you, I've report the bug of custom `<ws>` at rakudo issue.

although, now, I understand(?) how LTM works, does it mean that LTM works poorly on `rule`s?

think of some users customarily add whitespace between term in `rule`, LTM always works only on the first declarative prefix. at least it is a trap

**Comment by raiph** [comment]
On Mon, Oct 30, 2017 at 2:21 PM, Alex Chen <notifications@github.com> wrote:

> @smls <https://github.com/smls> thank you, I've report the bug of custom
> <ws> at rakudo issue.
>
As @smls wrote, it is not a Perl 6 or Rakudo bug, only a doc bug.

> does it mean that LTM works poorly on rules?
>
I'd say LTM works nicely for both `token`s and `rule`s.

But I think I know what you mean, as explained below.


> think of some users customarily add whitespace between term in rule,
> LTM always works only on the first declarative prefix.


Terminating LTM at whitespace in `rule`s is the only thing
that `rule`s do that is different from what `token`s do.

If a user wants to add whitespace between their terms,
*and have that whitespace ignored by the tokenizer*, the
solution is clear: use `token` instead of `rule`.


> at least it is a trap


I'm not seeing that way at the moment despite your surprise.

--
raiph

**Comment by W4anD0eR96** [comment]
@raiph what said was a bug is about the user-defined <ws>.

I agree with your explanation, they should use `token` instead of `rule`, but how can someone doesn't familiar with them know that? Thus I think it may be a trap, or, at least a hint/note when we doc   `|` alternations

**Comment by raiph** [comment]
> @raiph what said was a bug is about the user-defined <ws>.

Gotchya.

> I agree with your explanation, they should use token instead of rule, but how can someone doesn't familiar with them know that?

Presumably someone not familiar with `rule` would search for it in p6doc.

A search for `rule` in p6doc lists a couple rule related entries. `rule (declarator)` links to [Named Regexes](https://docs.perl6.org/language/grammars#Named_Regexes). This section mentions `rule` at the end. It says "The only difference between the token and rule declarators is that the rule declarator causes `:sigspace` to go into effect:" followed by some basic examples. The `:sigspace` links to the Sigspace section of the languages/regex page. That section discusses :sigspace in detail. I note also that the page has another relevant section, Matching Whitespace, but the sigspace section doesn't link to it.

Is this good enough? Perhaps not. Some issues:

* A `rule` can be unnamed. So linking `rule (declarator)` to Named Regexes is a bit weird. Perhaps link to some better location? Or add another entry to the list of results for a search for `rule` that links to a better location?

* Folk may not have the patience to read till the end of the section to see the bit about `rule`s.

* If someone fails to click on `:sigpsace` they may think they know what `:sigspace` does, and hence may think they know what `rule` does. Perhaps make it clearer that the examples listed are just the basics and folk ought to follow the `:sigspace` link to properly understand what a `rule` does?

* Maybe the Sigspace section of the languages/regex page ought link to the Matching Whitespace section of the same page?

**Comment by W4anD0eR96** [comment]
@raiph  your opinions are worthy and comprehensive.

Recently I am going to work on docs about regex, include `/language/regex`, `/language/grammar`, `/type/Match` and so on.  I will take your opinions into consideration carefully.

However, it's a little far from the topic of the issue. So maybe we can keep contact in other way, such as e-mail.
