### ISSUE TITLE
Grammar .parse, details about *%opt needed

### ISSUE THREAD

**Issue by TisonKun** [perl6/doc#1651]
now the doc is

https://github.com/perl6/doc/blob/39539835bf833d3b8251e63a4f8504eda0e87d58/doc/Type/Grammar.pod6#L87-L101

I have try :
```
grammar RepeatChar {
    token start($character) { $character+ }
}

say RepeatChar.subparse('bbbabb', :rule('start'), :args(\('b')), :g);
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('B')), :i);
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('B')), :i, :pos(4));
say RepeatChar.subparse('bbbbbb', :rule('start'), :args(\('b')), :i, :pos(4));
```

but the results are too confusing.

since it says

https://github.com/perl6/doc/blob/39539835bf833d3b8251e63a4f8504eda0e87d58/doc/Type/Grammar.pod6#L60

more details about `*%opt` are needed. Otherwise not all adverbs are allowed.

**Comment by moritz** [comment]
@TisonKun there are several type of adverbs that a regex can have. Some of the apply at compile time, like `:s`, `:i` etc. You cannot pass those to `.parse`, because the regexes have already been compiled.

But, you can pass those adverbs that affect the run time behavior, such as `:pos`, `:continue`, are interpreted here.

Does that make sense?

**Comment by TisonKun** [comment]
@moritz yes. thank you for the clear explanation~
