### ISSUE TITLE
Explain what “backtracking” is

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#1671]
Maybe we can simply link it to https://docs.perl6.org/language/regexes#Ratchet, although I'd much rather have a separate section about it.

**Comment by W4anD0eR96** [comment]
Should it also be in Glossary?

**Comment by fluca1978** [comment]
I've created a branch <https://github.com/perl6/doc/tree/fluca1978-backtracking> that provides a dedicated section with an example, as well as a term in the glossary.
I've placed the section at the end of the regexes page, since I'm not sure it should be on a top position.

If that is ok I can merge, otherwise reword, please suggest any improvment.
