### ISSUE TITLE
Missing block (apparently claimed by 'X::MyApp::Error')

### ISSUE THREAD

**Issue by anopperl** [perl6/doc#1688]
react {
  whenever Supply.from-list(1 .. 10) -> $v {
    say $v;
    LAST { say 'Job is done.' },
    QUIT { when X::MyApp::Error { say "App Error: ", $_.message }};
  }
}

when i run this code it give error 

Function 'X::MyApp::Error' needs parens to avoid gobbling block (or perhaps it's a class that's not declared or available in this scope?)
------> :Error { say "App Error: ", $_.message }⏏};
Missing block (apparently claimed by 'X::MyApp::Error')
------> :Error { say "App Error: ", $_.message }⏏};

**Comment by jnthn** [comment]
That isn't a snippet that will run in isolation; it expects that a `class X::MyApp::Error is Exception { }` or similar will already have been declared. Perhaps there's a way we can change the example to something that will run on its own, however.

**Comment by anopperl** [comment]
see 

https://user-images.githubusercontent.com/16158099/33267583-0841dccc-d3a0-11e7-91b3-994c80e40df7.png

**Comment by coke** [comment]
See:

https://github.com/perl6/doc/blob/master/doc/Language/concurrency.pod6#L401

Note that most of the code snippets are tested to make sure that they at least compile; because this is user-facing documentation, we don't necessarily want show all the steps to make each snippet compilable, instead we try to highlight the thing we're actually demonstrating. Here we have a preamble that has exactly what @jnthn suggested.

You've already dealt with the missing $supply, I think dealing with the sample exception (which we've tried to mark as clearly not a rakudo core exception) is just the next step in integrating this sample into your codebase.
