### ISSUE TITLE
Contributing guide for nbsp in "Perl 6" / "Perl 5"?

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1719]
Went in to drop a handy one-liner that converts "Perl 6" / "Perl 5" with spaces into non-breaking space version, but didn't find where this stuff is even mentioned in our contributing guides.
```
perl -C -pi -e 's/Perl (6|5)/Perl\x{A0}$1/g'  SOME-FILE
```

**Comment by fluca1978** [comment]
Added something to the STYLEGUIDE.md, I believe this could be useful to prevent others do my very same error. If that sounds ok, please close the issue, otherwise comment out and I will keep working on it.

I'm also thinking if we should include some kind of automatic non-breaking script within the htmlify.p6 one (or before in the build chain) to fix these kinds of mistakes.

**Comment by zoffixznet** [comment]
👍 Looks great. Thanks!
