### ISSUE TITLE
Any.exit should be there?

### ISSUE THREAD

**Issue by fluca1978** [perl6/doc#1747]
The sub exit is documented as part of Any <https://docs.perl6.org/routine/exit> but that is not really true:

```
> Any.exit;
No such method 'exit' for invocant of type 'Any'. Did you mean 'emit'?
  in block <unit> at <unknown file> line 1
```

Now, as far as I understand, exit is really implemented within the Rakudo (from Internals.pm):

```
Rakudo::Internals.REGISTER-DYNAMIC: '&*EXIT', {
    PROCESS::<&EXIT> := sub exit($status) {
        state $exit;
        $exit = $status;

        once {
            Rakudo::Internals.THE_END();
            nqp::exit(nqp::unbox_i($exit.Int));
        }
        $exit;
    }
}
```

If that is correct, should we move &exit from Any to another place?
Suggestions?

**Comment by JJ** [comment]
Yes to the first, I have no idea where to move it. I want to say Int, but
it seems to be the only subroutine that is not assigned meaningfully to any
class. Most subs are grouped by arguments, so it makes as much sense as
anywhere else, I guess.

**Comment by fluca1978** [comment]
My objection to keeping it under Any is that it could lead to invoking Any.exit resulting in a fault.
While it is clear it is a sub, I don't see the point in keeping it in Any since it also not declared in Any.pm.
I agree it's a minor problem, do we have similar cases that lead to a collection of "nowhere" subs?

**Comment by JJ** [comment]
It really depends on what you want to call "nowhere" subs. Is `cas` part of
`atomicint` the way it is now? https://docs.perl6.org/routine/cas? Do we
group them by its first argument? In that case exit would go to Int.
Otherwise, the box of thunders would open and we would have to really
review every single sub to see where it should go...

**Comment by JJ** [comment]
It's quite clear, anyway, that it does not belong to `Any`

**Comment by fluca1978** [comment]
Isee the point, but while it is quite clear that `cas` is something related to `atomicint`, even if not belonging to it, it is not clear (at least to me) why `exit` should be within the `Any`.

I mean, while reading the documentation for `atmicint` I could be interested in which subroutines can work on such type, `cas` as an example.
While reading `Any`, am I interested in reading about `exit`?

However, given that &exit will stay on Any, can we at least remove the following comment from &exit (it could confuse others):

`=comment` TODO maybe find a better place to document &exit

**Comment by JJ** [comment]
Is it going to stay on Any? Is that settled? I'm all for finding a better place.
My point, anyway, is do we document subroutines in the class they are "somewhat related to"? And do we define "somewhat related to" as "using it as first argument"? I that case the "better place" for exit would be "Int". I don't know, maybe we should leave the comment as it is now...

**Comment by fluca1978** [comment]
I agree: we need a formal rule to decide "how" a sub is related to a class.
In the case of `cas` + `atomicint` I believe it is straightforward. In the case of `exit` and `Any` I don't.
Could it be that such loosely related routines need to be pushed up to `Mu`?
Could be that such loosely related routines are grouped into a "routine" separated page?

I surely don't agree to move `exit` to `Int` because, while I could see a trick in believing that `exit` could be somewhere up in the inheritance chain, I would not expect to be related to `Int` that reminds me numeric operations. The fact is, I do believe `exit` should at least stay within `Proc` or alike, even control flow seems to me a more reasonable place at the moment.

**Comment by JJ** [comment]
2018-01-26 9:51 GMT+01:00 Luca Ferrari <notifications@github.com>:

> I agree: we need a formal rule to decide "how" a sub is related to a class.
> In the case of cas + atomicint I believe it is straightforward. In the
> case of exit and Any I don't.
> Could it be that such loosely related routines need to be pushed up to Mu?
>

I would definitely go for that.


> Could be that such loosely related routines are grouped into a "routine"
> separated page?
>

It would probably be better. I'm not sure about the plural, though. So far
I haven't been able to find any other example.


> I surely don't agree to move exit to Int because, while I could see a
> trick in believing that exit could be somewhere up in the inheritance
> chain, I would not expect to be related to Int that reminds me numeric
> operations. The fact is, I do believe exit should at least stay within
> Proc or alike, even control flow seems to me a more reasonable place at
> the moment.
>
The problem is that "loosely related to" is, literally, not precisely
defined. That's why I said all hell would break loose. Your proposal to
move it to Mu would be OK, except it's only related insofar Mu is related
to everything. A new "routines" page would probably be better.

**Comment by gfldex** [comment]
`exit` is somewhat related to `MAIN`. So that might also be a good spot. One could even argue that it's related to `return`. Even though it's a sub, it behaves more like a control exception.

I would be careful with a "formal rule" because that requires the reader to know the rule. And then we have to decide where to doc that formal rule.

**Comment by JJ** [comment]
... That's, however, a smaller problem than having no rule or informal rule and deciding on a case by case basis. We can put the doc in the CONTRIBUTING file, for instance; there are already rules like that there.

**Comment by fluca1978** [comment]
I agree with setting some sort of rule to keep the documentation coherent.

With this particular case as an example, I do believe there should be a kind of "low level" functions to document.

**Comment by JJ** [comment]
That would be a different issue. I agree with @gfldex . Besides, that wouldn't need another new document to create.

**Comment by JJ** [comment]
Just a ping to see if we have an agreement of what to do in this case. Create a new page for "low level" functions? Any thoughts on this @coke @AlexDaniel @zoffixznet ?

**Comment by fluca1978** [comment]
I sligtly changed my mind: while I still believe we need a kind of "low level" operators page, I suspect for this particular case a "control flow" page could be clearer (it would contain MAIN, not-main and exit).

**Comment by JJ** [comment]
And return?

**Comment by fluca1978** [comment]
It could be a "program control flow" (main, exit, ...) and "method control flow" (entry point and return), so that also other stuff (phasers?) could be managed. I suspect the point right now is to find out how many "low level" operators we have, if we have just a few than I would go for this solution, if we have a discrete number than produce a low level page.

**Comment by zoffixznet** [comment]
> Any thoughts on this @zoffixznet ?
> My point, anyway, is do we document subroutines in the class they are "somewhat related to"? And do we define "somewhat related to" as "using it as first argument"?

I think the reason many subs are documented in the docs for a particular class is because a lot of subs are just a functional versions of a method call: `chars "foo"` vs `"foo".chars`, `elems <a b c>` vs `<a b c>.elems`.

For subs that don't fit that pattern, we could perhaps just document them on some separate page, in thematical sections, a lot how we have the Operators page done: https://docs.perl6.org/language/operators

**Comment by JJ** [comment]
It could be a "control flow" page. We could include sections on program and method control flow.

**Comment by zoffixznet** [comment]
Briefly skimming through the [Routine Map](https://map.perl6.party/) there's many non-control-flow subs that don't have a method equivalent: `roundrobin`, `undefine`, `prompt`.

Including these that kinda-sorta fit other places, but still: `term:<now>` and `term:<time>` (currently documented as on Terms page), `slip`, `pair`, `set`, `bag`, `mix`

**Comment by JJ** [comment]
So OK with a "control flow" page? Something else?
