### ISSUE TITLE
"Item and List Assignment" section is dense

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#1810]
IMO https://docs.perl6.org/language/variables#Item_and_List_Assignment is trying to answer too many un-asked questions.

I'd cut it in half, removing everything starting from *"For instance, if the internal assignment is a declarator, item assignment is used, which has tighter precedence than both the comma..."*

That part just drones on about all the various permutations of assignment and declarations made within statements, which [causes some confusion](https://irclog.perlgeek.de/perl6/2018-03-03#i_15881093).

The first half of that section along with operators page seems to describe all of needed content. If the user wishes to know how various permutations behave, they can experiment at will.

**Comment by jimav** [comment]
By nature I want to know how things <i>really</i> work, not just the abstract model.  So I like it when docs point out deeper implications along the way, because it reduces cognitively unresolved forward references.

**Comment by jimav** [comment]
In this case the doc has some LTA examples which seem to say that the presence of a declarator such as `my` can change whether list or item assignment occurs.  I don't understand this because the examples given do not demonstrate any difference in behavior (the results are the same).

<b>Suggestion:</b> Provide examples where `my @array = ...` and `@array = ...` (for the same `...`)  actually have different results.

In the example

    @array = $num = 42, "str";  # list assignment 

the surrounding text implies the comment refers to the  "internal assignment" (presumably of `$num`).   But if the compiler gives list-assignment context to the internal `=`, why isn't the rest of the RHS sucked up causing a <i>Useless use of constant string "str" in sink context</i> error?   This contradicts what I thought I learned about list assignment context.   And, again, the results of both the list and item assignment examples are identical.
