### ISSUE TITLE
The Grammar section could use a warning about using regexes inside an Action.

### ISSUE THREAD

**Issue by drforr** [perl6/doc#1853]
Specifically, if you write code like:

--cut here--
method TOP( $/ ) {
    my $v = ~$/ ~~ /foo/;
}
--cut here--

attempting the /foo/ match fails because $/ is a readonly argument resulting in the error below:

--cut here--
Cannot assign to a readonly variable ($/) or a value.
--cut here--

which is entirely correct, but it may not be obvious that $/ is readonly because you're passing the match as an argument. Granted, it's right there a few lines above, but it confused me.

Maybe the error could be changed to:
--cut here--
Cannot assign to the argument $/.
--cut here--

in this case.

**Comment by JJ** [comment]
Hi, Jeff. Thanks for dropping by. It's not clear what you mean here, maybe because some characters were dropped. Can you please revise and rewrite if possible? Seems like you are referring to something happening inside the if statement, but there's nothing there... Also if you mean that the error mensage should be changed, that would be rather a Rakudo issue, I guess.

**Comment by drforr** [comment]
Edited per request - the if{} block isn't necessary to trigger the issue. I don't know if it's worth a rakudobug because it's very much specific to grammar actions, so I thought it might be more appropriate as a documentation issue in the Grammar section.
