### ISSUE TITLE
Accidental `markdown`

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2022]
Grep the whole doc repository like this:
```bash
ack '`.*`'
```
And you will find a lot of cases like:
![image](https://user-images.githubusercontent.com/5507503/39882777-775f47ca-548d-11e8-97e9-312599550095.png)

Close this issue when all uses of `` ` ` `` were replaced with `C<>` (comments in code are OK).

**Comment by JJ** [comment]
And probably add a test for that too, right?

**Comment by JJ** [comment]
Um, probably not that.

**Comment by AlexDaniel** [comment]
If you see a way to do that, then yes.

**Comment by JJ** [comment]
There are also links... https://docs.perl6.org/language/community.html And
those are my fault.

**Comment by JJ** [comment]
* [ ] doc/Language/traps.pod6
1498:another variable in the signature or add `is copy`, this way:

* [ ] doc/Language/regexes.pod6
480:The quantifier interacts with `%` and controls the number of overall

* [ ] doc/Language/concurrency.pod6
502:caching mechanism where lack of value returned by `.poll` is a signal that

* [ ] doc/Language/subscripts.pod6
387:               more than just subscripts, i.e. also routines like `push`), at

* [ ] doc/Language/modules.pod6
373:You can combine `EXPORT` with type captures for interesting
374:effect. This example creates a `?` postfix which will only work on
575:The C<name> key is compulsory, and `zef` will fail if you do not include it. Even if you have created a META6.json file just to express the dependencies for a series of scripts, this section must be included.

* [ ] doc/Language/unicode.pod6
69:come out as something like `?xFF`.

* [ ] doc/Language/nativecall.pod6
134:When working with native functions, sometimes you need to specify what kind of native data structure is going to be used. `is repr` is the term employed for that.

* [ ] doc/Language/5to6-nutshell.pod6
1365:my $captured = `echo \Q$arg\E`;
1372:my $captured = `echo $arg`;
1719:Perl from a source distribution. The `perl` executable analyses and
1723:`perl` executable will save those details to an XML file, which can then be

* [ ] doc/Language/5to6-perlfunc.pod6
540:There is no built-in `fork` function. While it's possible to call it using
544:`fork` only clones the thread that called `fork`, resulting in a process that
550:threads is pretty much assured, and there's no reasonable way to make `fork`

* [ ] doc/Language/syntax.pod6
297:If instead we had declared `dice` as a regular `sub dice() {
298:(1...6).pick }`, the expression `dice + dice` would be parsed as
299:`dice(+(dice()))`, resulting in an error because `sub dice` expects zero

* [ ] doc/Language/performance.pod6
52:Routines with a filename that starts like `SETTING::src/core/` or `gen/moar/` are

* [ ] doc/Type/X/TypeCheck/Return.pod6
5:=SUBTITLE Error due to a failed typecheck during `return`

* [ ] doc/Type/X/Syntax/UnlessElse.pod6
5:=SUBTITLE Compilation error due to an `unless` clause followed by `else`

* [ ] doc/Type/X/Syntax/NoSelf.pod6
5:=SUBTITLE Compilation error due to implicitly using a `self` that is not there

* [ ] doc/Type/X/Syntax/Augment/WithoutMonkeyTyping.pod6
5:=SUBTITLE Compilation error due to augmenting a type without `MONKEY-TYPING`

* [ ] doc/Type/X/Syntax/Self/WithoutObject.pod6
5:=SUBTITLE Compilation error due to invoking `self` in an ineligible scope

* [ ] doc/Type/Cursor.pod6
41:Returns the current position as a string index into `Cursor.target`.

* [ ] doc/Type/Routine.pod6
5:=SUBTITLE Code object with its own lexical scope and `return` handling

* [ ] doc/Type/Compiler.pod6
10:through C`compiler` attribute of the the L«C<$*PERL>|/language/variables#Dynamic_variables» dynamic variable.

* [ ] doc/Type/Rational.pod6
11:and denominator (C<DeT>). By default, these are C<Int>, but other types of `Rational` are possible by using a different parameterization
18:Please note that, since `DeT` is by default equal to `NuT`, in this case both are instantiated to C<UInt>. Built into Perl 6 are L<Rat> and L<FatRat>, which both do the C<Rational> role.

* [ ] doc/Type/Cool.pod6
1126:For that behavior, use the `:skip-empty` named argument:

**Comment by JJ** [comment]
If we want a test for this, please open a different issue...
