### ISSUE TITLE
So what the hell is react/whenever

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2135]
*Note: Please feel free to reword the title. I'm just frustrated with how little our docs say about such an important feature of perl 6.*

Imagine you stumbled upon react block somewhere in the wild, so you go to the documentation to learn about it.

The search functions gives you just one link: https://docs.perl6.org/language/concurrency#index-entry-react-react

The section starts with:

> This could also be written using the react keyword:

Sorry, what can be written? The previous section takes a full page and talks about supplies and suppliers, and moreover that's not needed at all to understand react (IMO). The basics can be shown with simple promises.

Then it goes with the only paragraph that explains react block:

> Here the whenever keyword uses .act to create a tap on the Supply from the provided block. The react block is exited when done() is called in one of the taps. Using last to exit the block would produce an error indicating that it's not really a loop construct.

Uh… and? So if it's using taps, why use the react block instead of just using .tap? Nothing is explained.

----

If I had to summarize react block in one sentence I would say that it does *sequential processing of asynchronous events*. That, in my opinion, is its main feature. I don't know if this description is fully correct and if it is understandable, but perhaps that's a good start.

Moreover, it should probably discuss how exceptions happening in whenevers/react can be noticed easily, compared to threads dying in regular .taps.

FWIW there's a huge example using react/whenever in https://docs.perl6.org/type/Proc::Async (maybe it can be used for inspiration).

**Comment by bduggan** [comment]
>If I had to summarize react block in one sentence I would say that it does sequential processing of asynchronous events. That, in my opinion, is its main feature. I don't know if this description is fully correct and if it is understandable, but perhaps that's a good start.

I usually say "`react` declares an event loop".

**Comment by jnthn** [comment]
I'm quite fond of this [minimal web crawler example](https://gist.github.com/jnthn/b358ebfb6ea6c366834896b9f62ba92b) for introducing `react`/`whenever`, in that it allows for discussion of various key things that the construct does:

* The responses to the web requests may arrive on multiple threads, but we will only be inside the code of the `react` block processing one of those at a time. Thus the state declared in the `react` block is protected.
* The `react` block lives so long as there are outstanding `whenever`s to be run
* The `whenever` construct is dynamic in nature - that is, you can run it many times within a single `react` block's lifetime
* Any unhandled exception is propagated to the code that started the `react` block

Besides that, the problem is:

* Practical
* Something many developers would be able to relate to, or at least understand the problem being solved
* Notably trickier if you weren't using `react`/`whenever` (error handling and completion handling would need to be done manually)

The downside of course is that it has an ecosystem dependency. But even if it's not taken verbatim, I hope it provides an indication of what properties of `react`/`whenever` are especially worth calling out in whatever examples are used to discuss it.

**Comment by AlexDaniel** [comment]
I'm against using that example. In addition to downsides already mentioned, it's overly complicated (for docs) and doesn't really solve the actual problem of web scraping (the code is allowed to do thousands of requests at the same time, so why show an example that is flawed). The code is cool but is just not suitable for docs.

**Comment by jnthn** [comment]
> it's overly complicated (for docs)

Yeah, and the reason it doesn't include the request throttling was to keep the example size manageable. :-)

I spent quite a lot of time teaching reactive programming in the past, and found that the simplest examples are on the one hand perhaps OK to understand, but generally don't motivate why on earth you'd want to use this paradigm. However, it's hard to show the latter without having gotten through the former. I certainly don't think something equivalently complicated would make a good *first* example (or even second or third example), but it's probably good to figure out something of around that size to show `react` and friends in a more practical context.

**Comment by nxadm** [comment]
>  I spent quite a lot of time teaching reactive programming in the past, and found that the simplest examples are on the one hand perhaps OK to understand, but generally don't motivate why on earth you'd want to use this paradigm.

Maybe just use the simplest possible example in the docs and refer to a examples/tutorial page for a more realistic (and copy-pastable) example?

**Comment by MorayJ** [comment]
I hope this is now answered, though probably only briefly. There's probably scope to open an issue on the whole page just to make sure it's all clear, and probably more examples could be added.
