### ISSUE TITLE
"I don't know what's introductory in perl6/doc"

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2145]
> \<jmerelo\> AlexDaniel: but I don't know what's introductory in perl6/doc.

So I went to [Language Documentation](https://docs.perl6.org/language.html) wearing the hat of a new user, and… I don't know either.

The documents are sorted alphabetically, so the very first thing I'm presented with is "Classes and Objects", and the second one is "Concurrency". One of the introductory topics—"Variables"—is very last in the list.

There's also a second problem with alphabetical sorting: related topics are quite far apart in the list: "Classes and Objects", "Object Orientation", and "Meta-Object Protocol" are related topics, yet the they're some ways apart from each other. We have "Functions" describing subs and "Routines" listing a few of core routines, and if I spotted the latter first, I might've assumed that's all there were for "functions" documentation.

I'd suggest better ordering than alphabetic: order by difficulty, starting with most basic concepts first. I think some subsections grouping related topics could also be useful.

**Comment by JJ** [comment]
Related to #1969 and maybe to #1823, if it's the page itself what's going to be changed. Maybe create a new front page would be a solution, but that would be major. Maybe simply creating a new page with all those pages (OK, maybe not all of them) in a logical order would be a second best.

**Comment by stmuk** [comment]
Note that originally the 5to6 pages appeared at the top.

See https://web.archive.org/web/20151128202454/https://docs.perl6.org/language.html

This sort of order is still used by the single page version of the docs.

https://docs.perl6.org/perl6.html 

Probably because pod2onepage still orders based on filename alphabetical sort rather than title.

This sort of order was convenient since it meant a intro for perl 5 users was at the top but the ordering probably should be more explicit and less fragile.

If we went back to this ordering then there probably needs to be another section a more general non-language specific intro basic tutorial above the perl 5 one. I don't think it should be long and it mostly should plug perl6intro.com but a short example might be nice. It might be possible to reuse existing content from the dead perl6 book at 

https://github.com/perl6/book 

or even jnthns slidedeck which ships with star at

https://github.com/rakudo/star/blob/master/docs/2015-spw-perl6-course.pdf

**Comment by tbrowder** [comment]
The current ordering is by alpha sort on the title whis extracted from inside the page. By adding a config tag and desired sort order value on the “=begin pod” line we can have instant sorting by a slight tweak from title to tag value.

**Comment by stmuk** [comment]
2cfbe8035e933bcc8dee6e966c6cff64fb18d3c2 as a "quick fix"

**Comment by tbrowder** [comment]
I have I believe a working soultion I will submit as a PR after I get it cleaned up a bit later today.

**Comment by tbrowder** [comment]
I think we’re on track to satisfying this, and this issue can be closed soon.

**Comment by stmuk** [comment]
There is now an introductory example (pinched from the old perl 6 book) at the top of 

https://docs.perl6.org/language.html

**Comment by JJ** [comment]
Would the example above satisfy this issue?
