### ISSUE TITLE
Remove suggestion to wait for Star releases 

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2149]
This was meant to be a PR, but I clicked the wrong button: https://github.com/perl6/doc/commit/166afeaf4a603b1660aa113d4912446ef8058547

If there's a problem/disagreement with that commit, simply revert it.

Filing and closing this Issue to generate a notification.

**Comment by AlexDaniel** [comment]
The change looks correct:
* We should not have many compiler-specific notes
* Any compiler-specific remarks should be marked as such
* If there is something to be said about the version, it should say “starting with rakudo 20xx.xx” or something similar
* So why wait for a star release if required version is clearly marked? It feels like that point was written with pre-Christmas mentality when things were going in and out willy nilly.

**Comment by AlexDaniel** [comment]
Also, for the most part, I'm only expecting outstanding bugs and quirks in compilers to be mentioned (see #1486). The rest should be documented in terms of v6.c/v6.d and such. I know that this way of doing things is sometimes hard because [reasons](https://github.com/rakudo/rakudo/issues/1289), but we should be aiming for that consistently.
