### ISSUE TITLE
404 Pages have duplicated, overlaid Camelias

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2228]
E.g. on https://docs.perl6.org/routine/DEPRECATED
![untitled](https://user-images.githubusercontent.com/5747918/43368922-bb769718-9332-11e8-8e06-ec18ba887cac.png)

**Comment by JJ** [comment]
I understood this first as "The number of 404 pages has duplicated. Adding insult to injury, they also overlay Camelia". 
The problem is that one of them is in the background, and the other is, well, overlaid. I don't see it as a big problem. It's probably a lot of work (and some overengineering) to put one exactly over the other...

**Comment by coke** [comment]
I think this is a stylistic decision, not a bug. I'm OK with this look.

**Comment by zoffixznet** [comment]
> I think this is a stylistic decision

I'd call that amateurish if only it didn't look entirely broken.

**Comment by zoffixznet** [comment]
> to put one exactly over the other...

You don't. You remove one.
