### ISSUE TITLE
Non-operators are listed under operators

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#2267]
There are operators listed in https://docs.perl6.org/language/operators#postfix_. that claim to be postfix operators, but in fact, the constructs are just syntax and aren't operators at all.

I suspect original writers documented it this way because in most cases it wouldn't matter if it were an operator or just a piece of syntax. However, built-in operators can be referred to as a noun (e.g. `&infix:<,>`) and used a a Callable. The same isn't the case with syntax.

Briefly scanning [the page](https://docs.perl6.org/language/operators#postfix_.):

- postfix .
- postfix .&
- postfix .=
- postfix .^
- postfix .?
- postfix .+
- postfix .*
- postfix ». / postfix >>.

None of those are operators, I suspect there're more cases on that page with similar issue.

**Comment by JJ** [comment]
What do you suggest? Create a new "dot constructs" page? Off the top of my head, what do they have in common? The `.`?

**Comment by zoffixznet** [comment]
Dunno, I call them "methodops" because they're parsed with `methodop` token in rakudo. But they're not real operators.

I also wouldn't list `».` or `.&` the way they are listed, as it's really a combination of different things and things that can be combined are.

- non-hyper / hyper (`my @hyper = "", "»", ">>";`)
- plurality (don't know the proper name; just made this one up) (`my @plurality = "", |<? + *>;`)
- method / method name (`my @method-name = "foo", ｢"foo"()｣, ｢&foo｣, ｢$foo｣;` the `@foo` was also speculated and is even parsed in Rakudo, but doesn't work; personally, I'd leave it out from the docs for now)

So you get a ton of combinations:

```
$ perl6 -e 'my @hyper = "", "»", ">>"; my @plurality = "", |<? + *>; my @method-name = "foo", ｢"foo"()｣, ｢&foo｣, ｢$foo｣; .join.say for @hyper X "." X @plurality X @method-name'
.foo
."foo"()
.&foo
.$foo
.?foo
.?"foo"()
.?&foo
.?$foo
.+foo
.+"foo"()
.+&foo
.+$foo
.*foo
.*"foo"()
.*&foo
.*$foo
».foo
»."foo"()
».&foo
».$foo
».?foo
».?"foo"()
».?&foo
».?$foo
».+foo
».+"foo"()
».+&foo
».+$foo
».*foo
».*"foo"()
».*&foo
».*$foo
>>.foo
>>."foo"()
>>.&foo
>>.$foo
>>.?foo
>>.?"foo"()
>>.?&foo
>>.?$foo
>>.+foo
>>.+"foo"()
>>.+&foo
>>.+$foo
>>.*foo
>>.*"foo"()
>>.*&foo
>>.*$foo
```

**Comment by lichtkind** [comment]
i talked with liz and we agreed the preferable resolvement is to include the ops in some internal hash so they can references as ops and we dont need to document them as something special, but on other hand at least mention it they are special might help someone with future issues

**Comment by zoffixznet** [comment]
> to include the ops in some internal hash

But... they're *not* ops. There are no Callables behind them that get called or can be referenced.

**Comment by lichtkind** [comment]
yes,
but there is an precedence level  asociated with them and I just wanted reference that

**Comment by zoffixznet** [comment]
You can use an actual op on the same precedence level if all you want is a precedence level.

I don't understand why we have to make such a drastic change to the language and make fake ops for a large chunk of syntax. You can, for example, override other ops. You won't be able to override these. So we're not solving anything with "internal hashes". It's just adding hacks to the compiler and confusion to the user all because someone misdocumented a piece of syntax.

And this is in an area that's already convoluted and doesn't quite work right. You may want to fix that first before adding more stuff to make things even more hacking and convoluted.

**Comment by lichtkind** [comment]
I'm just outsider (related to p6 coding) and trusted Liz suggestion. There are no changes I demanded.

**Comment by pmichaud** [comment]
On Thu, Aug 16, 2018 at 01:51:07PM +0000, Zoffix Znet wrote:
> > to include the ops in some internal hash
> 
> But... they're *not* ops. There are no Callables behind them that get called or can be referenced.

I don't know why there's a seeming insistence that something has to have a Callable behind it to be considered an "operator".

These *are* operators.  They parse like operators.  In fact, the parsing rule used to do it is named "methodop" -- the name itself recognizes that these are "operators" that are implemented as methods instead of infix/postfix/etc. callable subs.

There can certainly be some "operators" in the language that cannot be overridden (except syntatically), or that cannot be easily passed as functions to other operators.  AFAIK there's nothing that says an "operator" can only be those things that translates into Subs.

If there needs to be a name that distinguishes this class of "method operators" from other operators, I humbly suggest they be referred to as "methodops", and as needed they can be noted as syntatic implementations that cannot be overridden via the same mechanisms used for other types of operators.

But the language designers have always referred to things like "postfix ." as "operators", even though they're implemented as syntactic constructs instead of the standard sub-call form of an operator.  That's the natural place they should be documented.

Pm

**Comment by pmichaud** [comment]
...indeed, in many classical languages the "operators" have been syntactic constructs identified by the language definition, with no "Callable" behind them available to the programmer.  This use of the term "operator" includes even sibling languages such as Perl 4 and Perl 5.

Pm

**Comment by 2colours** [comment]
It's interesting to read up on these all discussions and I'm more than happy that I could agree with Patrick Michaud and disagree with Zoffix Znet for once. By the same logic, a whole lot of languages would have no right to speak about operators - and also, I wonder if the specs **mandate** that syntactic operators **shan't** be implemented as first-class routines. What if somebody manages to invent a super abstract model that can handle method calls as a first-order thing?
