### ISSUE TITLE
whenever can be used in a supply block

### ISSUE THREAD

**Issue by frithnanth** [perl6/doc#2292]
## The problem

In [https://docs.perl6.org/language/concurrency](Concurrency), the `whenever` keyword seems limited to appear only in a `react` block, while it can appear also in a `supply` block.

## Suggestions

Example:

```perl6
my $barman = supply {
  whenever Supply.interval(60) {
    done when * > ∞;
    emit "🍺";
  }
}
$barman.tap: { say "Got: $_" };
await $barman;
```

**Comment by MorayJ** [comment]
Can react be used without 'whenever'? I would probably be looking to have a headline for 'whenever' rather than 'react and whenever', and putting the supply example under that by saying you can also do this using the 'whenever' keyword. And then having just 'react' as a headline and saying that react has to use the 'whenever' keyword, as per the example if that sounds about right...

**Comment by jnthn** [comment]
> Can react be used without 'whenever'?

There's no obvious use I can think of for that, no. For `supply`, however, it *is* useful to use it without a `whenever`, if writing an async data source.

**Comment by MorayJ** [comment]
Hopefully this covers it, though possibly the whole page could do with a general revision, but I think whenever is in there now for supplies, which is important to have done.
