### ISSUE TITLE
404 page error for several terms that have trailing " "

### ISSUE THREAD

**Issue by ccube** [perl6/doc#2320]
## The problem
From the search bar under Perl 6 Documentation, I type "infix" and one of the choices is infix under syntax. I click on that and I get a 404 error asking me to please report it here. Done!

Besides that one, there are others:

 * [x] infix
 * [x] The
 * [x] Community

**Comment by JJ** [comment]
Thanks for reporting this. I'll check it out momentarily.

**Comment by JJ** [comment]
Just to document the progress, this is happening where the document generation is writing the file. The page is generated correctly, but for some reason it does not get written, or not written to the correct place. The error is somewhere in htmlify.p6, which makes it a bit difficult to track because #1823
