### ISSUE TITLE
A booboo and an rfe in contains documentation

### ISSUE THREAD

**Issue by ToddAndMargo** [perl6/doc#2334]
Hi All,

Over on 
    https://docs.perl6.org/routine/contains#(Str)_method_contains
the return  value is missing: --> Bool

Since it need to be updated anyway, for clarity, would you please consider the following enhancements:

Old:           multi method contains(Str:D: Str:D $needle, Int:D $pos)
Proposed: multi method contains(Str:D $Haystack : Str:D $Needle, Int:D $Position --> Bool)

Giving the input string the name "Haystack"  gives meaning to the parameter of "Needle".  You are searching for the "needle in the haystack".  Without this linkage, one is left wondering what the "needle" is "sticking".

The " :", rather than ":" makes it more clear that it is a delimiter to the untrained eye.

And spelling out "Position" just makes it clearer what it is.  (Not "pos" for Positive or what ever else it can be mistaken for.)

Many thanks,
-T

**Comment by finanalyst** [comment]
- Adding return type is needed.
- Changing style from lower case to sentence case (eg. $needle -> $Needle) will make this definition stylistically inconsistent with other documentation. I support keeping all variable names lower case.
- surrounding the `:` after the invocant with whitespace to indicate it is different from say `:D` is a fundamental change in style that would affect all documentation. At this point, the marginal benefit seems much less than the hassle of altering it everywhere else. Besides, once a person has understood the pattern, the whitespace becomes irrelevant.
- adding `$haystack` just to remind someone of the idiom seems like overkill. It raises other questions for a `newbie` user, eg. why is it given a special name when it isn't included in the method's calling signature?
- expanding pos -> position. If there is to be change, then why not something more explanatory, such as '$starting-from' ?

**Comment by Scimon** [comment]
I agree with your on most of these points except $haystack. There are other
methods where the invocant is renamed (words springs to mind after recent
discussions here) naming it $haystack makes the idiom easier to spot.

**Comment by JJ** [comment]
When the documentation says "defined as", it does literally what it says: it copies the definition from the source. In this case: https://github.com/rakudo/rakudo/blob/e54885e5e6d71bb6ab6d7f4eb86fe21dd9aee3de/src/core/Str.pm6#L175-L191

So changing the name of the variables to another one is not the usual way to do it. We can replicate the definition to make it more understandable, or otherwise explain it, but that's that. In that sense, as you see in the code I point to, the return type is not specified. That means just that: the only thing we know about "contains" is that it, apparently, returns a "Truish" value. The definition might be wrong, so what we do in these cases is to go to the test, in Roast: https://github.com/perl6/roast/blob/2288d4a3c543d72f822164dad529066ed055a0aa/S32-str/contains.t If it checks for a specific return value (like Bool), we can go back to Rakudo and request a change. But, as you can see in the source, it again just tests for a "Truish" value (that is, something that can be evaluated as True in a Boolean context).

So while I understand there's some need for clarification here, the code indicated can't be changed unless the source it's copied from is changed too. I propose to clarify the function of every parameter in the explanation, or simply replicate that definition to (maybe) make it clearer.

**Comment by ToddAndMargo** [comment]
On 9/26/18 9:59 PM, Richard Hainsworth wrote:
>   * Changing style from lower case to sentence case (eg. $needle ->
>     $Needle) will make this definition stylistically inconsistent with
>     other documentation. I support keeping all variable names lower case.

Fine with me.  I like it the other way, but I don't care that much.
I can type since I was 17 and upper and lower case fly off the
keyboard just as fast.  But, I do realize others "hunt and peck".
And, indeed it would break convention.

>   * surrounding the |:| after the invocant with whitespace to indicate
>     it is different from say |:D| is a fundamental change in style that
>     would affect all documentation. At this point, the marginal benefit
>     seems much less than the hassle of altering it everywhere else.
>     Besides, once a person has understood the pattern, the whitespace
>     becomes irrelevant.

Don't always presume the reader knows things like that.  They
are going to the docs for a reason.  They are there to learn things.

>   * adding |$haystack| just to remind someone of the idiom seems like
>     overkill. It raises other questions for a |newbie| user, eg. why is
>     it given a special name when it isn't included in the method's
>     calling signature?

If you use "needle" you also need to use "haystack".  Otherwise it
is insider information hidden from the reader.  "Needles" stick
things and go into pin cushions.  The reader wonders what you
are sticking.

If you do not use haystack along with needle, drop needle and
replace it with "substr".

>   * expanding pos -> position. If there is to be change, then why not
>     something more explanatory, such as '$starting-from' ?

I like "Starting-from" even better.  Great idea.

**Comment by b2gills** [comment]
The names of positional parameters is really only for human consumption.

So it does not matter if the names are different between Rakudo and the Docs.

Also the returns type isn't specified in Rakudo, but is (or should be) specified in ROAST.
So it should be specified in the Docs.

The main thing the docs should be concerned with, is that it follows ROAST.
(Which doesn't concern itself with the names of positional parameters, or invocants)

---

I don't see why it can't change to

```perl6
multi method contains(Str:D $haystack: Cool:D $needle --> Bool:D)
multi method contains(Str:D $haystack: Str:D $needle --> Bool:D)
multi method contains(Str:D $haystack: Cool:D $needle, Int(Cool:D) $start-position --> Bool:D)
multi method contains(Str:D $haystack: Str:D $needle, Int:D $start-position -->Bool:D)
```

---

Really rather than show multiple multi methods it could be just:

```perl6
multi method contains(Str:D $haystack: Str:D(Cool:D) $needle, Int:D(Cool:D) $start-position = 0 --> Bool:D)
```

If that is too long, we can split it into multiple lines

```perl6 
multi method contains(
  Str:D $haystack:
    Str:D(Cool:D) $needle,
    Int:D(Cool:D) $start-position = 0
  --> Bool:D
)
```

---

If the implementation had been written with just the one signature that was used above, then Rakudo will generate alternative multis, that just coerce the arguments.
(So calling `Str.^lookup('contains').candidates».signature` would return more signatures than were written.)

The only reason they are split up in Rakudo is for performance reasons.
(and that is getting to be less of an issue over time.)

**Comment by JJ** [comment]
El jue., 27 sept. 2018 a las 20:05, Brad Gilbert (<notifications@github.com>)
escribió:

> The names of positional parameters is really only for human consumption.
>
> So it does not matter if the names are different between Rakudo and the
> Docs.
>

But it does. It's simply the convention we follow. As I say above, there's
nothing against making a redefinition in the text. But "Defined as" is not
a creative interpretation of the definition. Is *the* definition. This is
the reference part of the documentation, and that is the convention that is
followed.

> Also the returns type isn't specified in Rakudo, but is (or should be)
> specified in ROAST.
>

It can or can not specify the return type, depending on how it's defined.
If the specification says it should return a Bool, roast follows that.
That's not the case. The specification is ambiguous at this point, simply
saying something that is evaluated to True. We don't know why, but that's
how it's defined, and "Defined as" is "defined as"

> So it should be specified in the Docs.
>

The specs in roast do not test for it specifically returning a Bool; it
tests for it returning something that can be coerced to Bool. The Docs, far
as I see it, shouldn't interpret creatively (or for the sake of the user) a
method or sub definition where the definition is to be copied. It can be
explained in the text, but not in that particular part.

> The main thing the docs should be concerned with, is that it follows ROAST.
>

Which they do. Roast tests, in this case, test for a "truish" value, not
for it being of type Bool.

> (Which doesn't concern itself with the names of positional parameters, or
> invocants)
>

(it concerns with being faithful to their definition in the source).

> ------------------------------
>
> I don't see why it can't change to
>
> multi method contains(Str:D $haystack: Cool:D $needle --> Bool:D)multi method contains(Str:D $haystack: Str:D $needle --> Bool:D)multi method contains(Str:D $haystack: Cool:D $needle, Int(Cool:D) $start-position --> Bool:D)multi method contains(Str:D $haystack: Str:D $needle, Int:D $start-position -->Bool:D)
>
> ------------------------------
>
> There are two parts to that. First, the name of variables: can't be done
because that's not how it's written in the source. Then, the return value:
can't be done because see first, and because second, it's not what it
returns. Check the source, it returns a Truish value, which varies
depending on the implementation, being nqp::bool (if memory serves) in some
cases, Bool in some other case. All can be coerced to Bool, and that's
what's tested in roast.

> Really rather than show multiple multi methods it could be just:
>
> multi method contains(Str:D $haystack: Str:D(Cool:D) $needle, Int:D(Cool:D) $start-position = 0 --> Bool:D)
>
>
That's certainly something we could do. However, the "defined as" section
of the reference manual says how it's defined in the source verbatim. We
could add another section and name it "don't read above, we really mean
this" or "TL;DR above, this is the real thing". But a reference section
should be accurate and precise, and that is what we strive to do here.

> If that is too long, we can split it into multiple lines
>
> multi method contains(
>   Str:D $haystack:
>     Str:D(Cool:D) $needle,
>     Int:D(Cool:D) $start-position = 0
>   --> Bool:D
> )
>
>
No we can't, since we actually test-compile those definitions and it will
fail if we split it in multiple lines. That's certainly something that can
be fixed, and in some cases multi-line definitions in Rakudo have to be
compressed to a single line. I'm afraid that's, however, a different issue.

------------------------------
>
> If the implementation had been written with just the one signature that
> was used above, then Rakudo will generate alternative multis, that just
> coerce the arguments.
>
But it has not. Just check the implementation, linked in the above issue.

The only reason they are split up in Rakudo is for performance reasons.
>

The only reason why we list them all is because we list them verbatim as
they are in the Rakudo source.

> (and that is getting to be less of an issue over time.)
>
If and when it changes, we'll try to reflect it in the "defined as" section
here.

**Comment by b2gills** [comment]
On Thu, Sep 27, 2018 at 1:22 PM Juan Julián Merelo Guervós <
notifications@github.com> wrote:

> El jue., 27 sept. 2018 a las 20:05, Brad Gilbert (<
> notifications@github.com>)
> escribió:
>
> > The names of positional parameters is really only for human consumption.
> >
> > So it does not matter if the names are different between Rakudo and the
> > Docs.
> >
>
> But it does. It's simply the convention we follow. As I say above, there's
> nothing against making a redefinition in the text. But "Defined as" is not
> a creative interpretation of the definition. Is *the* definition. This is
> the reference part of the documentation, and that is the convention that is
> followed.
>

No it does not.

There have been plenty of times that the names of parameters have changed
in Rakudo, and they didn't change in the docs.

Because they do no matter.

There have been plenty of times that multi methods have been combined, or
split up without changing the docs.

Because it does not matter.



> > Also the returns type isn't specified in Rakudo, but is (or should be)
> > specified in ROAST.
> >
>
> It can or can not specify the return type, depending on how it's defined.
> If the specification says it should return a Bool, roast follows that.
> That's not the case. The specification is ambiguous at this point, simply
> saying something that is evaluated to True. We don't know why, but that's
> how it's defined, and "Defined as" is "defined as"
>

Rakudo is not Perl 6.

Rakudo is an implementation of Perl 6 because it passes ROAST.

The documentation is about Perl 6.

That's why there is a disagreement about whether to document Rakudo
specific features.


> So it should be specified in the Docs.
> >
>
> The specs in roast do not test for it specifically returning a Bool; it
> tests for it returning something that can be coerced to Bool. The Docs, far
> as I see it, shouldn't interpret creatively (or for the sake of the user) a
> method or sub definition where the definition is to be copied. It can be
> explained in the text, but not in that particular part.
>

Zoffix has been going through the tests to improve them.

One of the improvements is to encode the result types.

He hasn't gotten to those tests yet.


> > The main thing the docs should be concerned with, is that it follows
> ROAST.
> >
>
> Which they do. Roast tests, in this case, test for a "truish" value, not
> for it being of type Bool.
>

ROAST doesn't concern itself with the names of the positional parameters.


> > (Which doesn't concern itself with the names of positional parameters, or
> > invocants)
> >
>
> (it concerns with being faithful to their definition in the source).
>

It concerns itself with being faithful to Perl 6, which is ROAST not Rakudo.

> ------------------------------
> >
> > I don't see why it can't change to
> >
> > multi method contains(Str:D $haystack: Cool:D $needle --> Bool:D)multi
> method contains(Str:D $haystack: Str:D $needle --> Bool:D)multi method
> contains(Str:D $haystack: Cool:D $needle, Int(Cool:D) $start-position -->
> Bool:D)multi method contains(Str:D $haystack: Str:D $needle, Int:D
> $start-position -->Bool:D)
> >
> > ------------------------------
> >
> > There are two parts to that. First, the name of variables: can't be done
> because that's not how it's written in the source. Then, the return value:
> can't be done because see first, and because second, it's not what it
> returns. Check the source, it returns a Truish value, which varies
> depending on the implementation, being nqp::bool (if memory serves) in some
> cases, Bool in some other case. All can be coerced to Bool, and that's
> what's tested in roast.
>

Seriously who the fsck cares?

Certainly not the people who maintain Rakudo.

Because like I've stated, they have changed things without changing the
docs.

Again because it is about Perl 6, not Rakudo.

> Really rather than show multiple multi methods it could be just:
> >
> > multi method contains(Str:D $haystack: Str:D(Cool:D) $needle,
> Int:D(Cool:D) $start-position = 0 --> Bool:D)
> >
> >
> That's certainly something we could do. However, the "defined as" section
> of the reference manual says how it's defined in the source verbatim. We
> could add another section and name it "don't read above, we really mean
> this" or "TL;DR above, this is the real thing". But a reference section
> should be accurate and precise, and that is what we strive to do here.
>

Then we should change the wording, because the Perl 6 docs should be about
Perl 6, not a particular implementation.

> If that is too long, we can split it into multiple lines
> >
> > multi method contains(
> > Str:D $haystack:
> > Str:D(Cool:D) $needle,
> > Int:D(Cool:D) $start-position = 0
> > --> Bool:D
> > )
> >
> >
> No we can't, since we actually test-compile those definitions and it will
> fail if we split it in multiple lines. That's certainly something that can
> be fixed, and in some cases multi-line definitions in Rakudo have to be
> compressed to a single line. I'm afraid that's, however, a different issue.
>

There have been plenty of times that the tests changed.
This is not a good argument.


> ------------------------------
> >
> > If the implementation had been written with just the one signature that
> > was used above, then Rakudo will generate alternative multis, that just
> > coerce the arguments.
> >
> But it has not. Just check the implementation, linked in the above issue.


So?


> The only reason they are split up in Rakudo is for performance reasons.
> >
>
> The only reason why we list them all is because we list them verbatim as
> they are in the Rakudo source.
>

Which is not useful to anyone.


> > (and that is getting to be less of an issue over time.)
> >
> If and when it changes, we'll try to reflect it in the "defined as" section
> here.
>

The docs are for people to understand what functions do what.

Forcing them to be consistent with one particular implementation is not
useful to anyone.

---

If you had been around you would know that there has been a careful
distinction between Perl 6 and Rakudo for a very long time.

Since the docs are on docs.perl6.org, they should probably be on the Perl 6
side not the Rakudo side.

**Comment by ToddAndMargo** [comment]
On 9/27/18 11:05 AM, Brad Gilbert wrote:
> Really rather than show multiple multi methods it could be just:
> 
> multi  method  contains(Str:D  $haystack:  Str:D(Cool:D) $needle, Int:D(Cool:D) $start-position=  0  -->  Bool:D)

I really love the single line, rather than having to trudge through
four lines to figure out which one applies.

Also, not to ask too stupid a question, but when annotating
an options parameter such as "$start-position", why do you guys
not stick with the subroutine convention of using a "?" for
optional parameters?  Something like "$start-position? = 0" and
that the default was 0.  Seems to me that it would make it very
clear what was happening.

multi  method  contains(Str:D  $haystack:  Str:D(Cool:D) $needle, 
Int:D(Cool:D) $start-position? =  0  -->  Bool:D)

If the "?" convention is something you guys like, I can always request 
it in a new RFE.  I think it really helps clarity things and keeps
from having to repeat the line over and over to state what is and
what is not optional


Also, is it necessary to use :D in Bool:D, as would it be very unusual
for a method to return a Nil?

**Comment by ToddAndMargo** [comment]
On 9/27/18 12:34 PM, Brad Gilbert wrote:
> The docs are for people to understand what functions do what.
> 
> Forcing them to be consistent with one particular implementation is not
> useful to anyone.

I really like the idea to have a tab in the docs that is just for
Rakudo specific stuff.  This would remove any ambiguity as to what was 
pure Perl and what was Rakudo specific.

**Comment by JJ** [comment]
El vie., 28 sept. 2018 a las 8:56, ToddAndMargo (<notifications@github.com>)
escribió:

>
>
> On 9/27/18 12:34 PM, Brad Gilbert wrote:
> > The docs are for people to understand what functions do what.
> >
> > Forcing them to be consistent with one particular implementation is not
> > useful to anyone.
>
> I really like the idea to have a tab in the docs that is just for
> Rakudo specific stuff. This would remove any ambiguity as to what was
> pure Perl and what was Rakudo specific.
>

Let me just point out that the definition of a function is not an
implementation detail, it's the signature of the function and, as such,
part of the specification. As you have pointed out, there are several
possible signatures that might be compatible with the specification, as
well as the fact that they are implemented as a multi and not a single
function, which might be implementation details, but still, the fact that a
particular signature is actually spec has to be proved; the signatures in
Rakudo (which are the ones included in the documentation) _have_ been
proved and are up to spec.

**Comment by ToddAndMargo** [comment]
On 9/30/18 9:22 PM, Brad Gilbert wrote:
> When people are reading the docs they care about how the function works 
> and how to call it.
> 
> They don't care that Rakudo uses 4 multis when one will suffice.
> 
> In fact it only serves to confuse them.
> 
> So by forcing the docs to conform to only the one implementation, the 
> documentation is worse than it could be.
> 
> This is the documentation for using Perl 6, not a document for how one 
> implementation decided to write it.
> If they want that, they should just read the source code.

Hi Brad,

I agree with everything you said.

But, (ya you can't be that lucky), Rakudo is what virtually
everyone uses.  So why not a section dedicated to Rakudo
specific issues?  Maybe even ask the Rakudo folks to maintain it?

Yes, it is a compromise, but it is a practical compromise.

-T

**Comment by CIAvash** [comment]
FWIW I agree that docs should be based on roast not Rakudo.

**Comment by b2gills** [comment]
[docs-change]: https://github.com/perl6/doc/commit/5e36e9da7073eabe55dc0631b75cd7bcf69a7a29?diff=unified
[source-unchanged]: https://github.com/rakudo/rakudo/blob/master/src/core/Promise.pm6#L88-L134

As an example of the docs not having to match Rakudo source, Zoffix [just changed the docs about `Promise.keep` and `Promise.break`][docs-change].

```diff
@@ -222,8 +222,7 @@ creates a chained promise.
￼
  =head2 method keep
￼
-￼     multi method keep(Promise:D:)
-     multi method keep(Promise:D: \result)
+     multi method keep(Promise:D: \result = True)
￼
  Keeps a promise, optionally setting the result. If no result is passed, the
  result will be C<True>.
@@ -242,8 +241,7 @@ taken. See method C<vow> for more information.
￼
  =head2 method break
￼
-      multi method break(Promise:D:)
-      multi method break(Promise:D: \cause)
+      multi method break(Promise:D: \cause = False)
￼
  Breaks a promise, optionally setting the cause. If no cause is passed, the
  cause will be C<False>.
```

Even though the [source hasn't changed][source-unchanged].

```perl6
    proto method keep(|) {*}
    multi method keep(Promise:D:) {
...
    multi method keep(Promise:D: Mu \result) {

...

    proto method break(|) {*}
    multi method break(Promise:D:) {
...
    multi method break(Promise:D: \result) {
```
