### ISSUE TITLE
$*DISTRO and other dynamic variables are incorrectly documented

### ISSUE THREAD

**Issue by pmurias** [perl6/doc#2510]
## The problem
https://docs.perl6.org/language/variables#index-entry-%24%2ADISTRO documents it as if it contained a string when in fact it's a Distro object

## Suggestions

Document is as what it is.

**Comment by JJ** [comment]
There are several problems with this. The first is not a big deal, it's the structure #2483 of the page, but that can be changed. The second one is that Distro is Rakudo specific. I have mentioned it in my change, but I have also changed the subject so that we can expand a bit on this. And thanks for raising the issue.
