### ISSUE TITLE
Should we start recommending .t6?

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#2576]
See https://github.com/ugexe/zef/issues/285

**Comment by jmaslak** [comment]
My thought: mi6 doesn't yet seem to support .t6 files.  We might want to add .t6 support to the various parts of the tool chain before recommending the use of .t6.

**Comment by JJ** [comment]
That issue was simply closed, not even with some little argument. And zef is the gatekeeper of this kind of things. If zef is not going to allow it, it does not make a lot of sense to use it elsewhere. Upstream from zef, at least we would have to look at prove, which is the default testing tool.
OTOH, I simply don't appreciate this kind of (no) response. It simply invalidates any opinion or discussion we might have somewhere else on the subject.
We can say that .t6 will allow editors to recognize them as written in Perl 6, as well as make easier accounting by GitHub, but the point is moot. zef is not open to allow them, that's it. Discussion finished.

**Comment by JJ** [comment]
The [commit recommends patching the Travis-CI script](https://github.com/ugexe/zef/commit/7cefbb2a8c784ec0ec5c4125e1b349454d056aed). As long as we're there, we could also change the rakudobrew-based one by something faster...

**Comment by jmaslak** [comment]
After work tonight I'll take a look at mi6 and submit a PR to support this in Mi6 at least. I looked through that code earlier and think it's straightforward.  I don't think prove needs to be patched (it just needs the proper option passed to know to look at p6 files).

**Comment by treyharris** [comment]
@jmaslak But prove _should_ be patched, since with no `--ext` arguments, it only looks for `.t` files, no?

**Comment by jmaslak** [comment]
Fair enough - it's not something that bothers me either way.  I call prove with an alias in my .bashrc anyhow so adding an argument isn't a big deal.

`alias 6prove="PERL6LIB=lib prove -e perl6"`

But I can see how having 6prove see .t6's automatically would make it easier for a new user.

**Comment by JJ** [comment]
Patching the Travis code might be more than enough. Linguist in GitHub too.

**Comment by AlexDaniel** [comment]
To answer my own question in OP, *not yet*.

Further discussion here: https://github.com/perl6/user-experience/issues/36
