### ISSUE TITLE
Object documentation 

### ISSUE THREAD

**Issue by isomorphisms** [perl6/doc#2617]
## The problem
Can there be a less boring example of objects than rect/points or names/last,first. Something that justifies the use of objects or would actually be useful/practical. Or at least silly.

**Comment by treyharris** [comment]
Would you like to suggest an example—perhaps one you've seen in other languages' docs? If you have good examples in mind—or have seen them elsewhere—we'd be delighted to look at incorporating them. Creating enervating and dull documentation is not our goal in this project!

With that said, I'm now going to give a rather long response here discussing what motivates the choice of an example like `Point/Rectangle` because a) I think the question belies a common misconception of the thought and care that does (or does not) go into choosing examples and b) issues formulated like yours are somewhat frequent and I'd like to get this down and point people at it in the future.

The `tl;dr` here is: choosing the subject of code examples is much harder than it may at first appear, and finding examples that are both accessible _and_ motivated can make "exciting" and/or "novel" a difficult and sometimes near-impossible additional request.

### The core issue with choosing topics of examples

As technical writers, the issue here is that there are competing demands for our description of the object model. These are even greater motivators in reference pages than in a tutorial page such as this one:

1. We're definitionally in some of the most "meta" parts of the docs when discussing how object orientation works, so any so-called "business logic" (syntax with attached semantics included to make the examples more concrete) are definitionally tangential.
1. The only way to completely avoid such tagential cruft in language documentation is to present the language constructs being introduced in abstract form (Backus-Naur Form, railroad diagrams, lambda calculus, UML, etc.)—thus, rather than introducing a simple two-property structlike and a slightly more complex consuming class, as in [clastut](https://github.com/perl6/doc/blob/dc5017c6a15f029b35527dd42e08570d115bfebc/doc/Language/classtut.pod6#L15), like this:
   ```perl6
   class Point {
       has Int $.x;
       has Int $.y;
   }

   class Rectangle {
       has Point $.lower;
       has Point $.upper;

       method area() returns Int {
           ($!upper.x - $!lower.x) * ( $!upper.y - $!lower.y);
       }
   }
   ```
   you would get a description of `class` assuming you could work out the syntax yourself---or, perhaps, if you were lucky, something as edifying as:
   ```perl6
   class A {
       has Int $.a;
	   has Str $.b;
   }
   class B {
       has A $.a-instance;
   }
   ```
   Most "serious" languages produced from the 1960's to the late 1990's were documented by academics and/or formal specifying committees, so this would be what you could expect. (Perl, as both a practical non-serious language and an empirical language wasn't burdened by such constraints.)
1. Given a choice between not giving examples at all, giving entirely meaningless examples, and meaningful examples, we have chosen to give more or less meaningful examples in many cases. (Not all, especially when we want to draw the readers' attention to an abstract concept and try to keep their attention off the "business logic" as much as possible—many of our metaprogramming examples are fairly abstract for this reason.)

Once the decision's been made given these competing interests to present concrete examples such as the one for `Point` and `Rectangle`, the problem becomes _what_ concrete thing can be used for an example? It needs to be something that

- will be instantly familiar to virtually all readers;
- is simple enough so that the reader does not become overwhelmed by (or—we hope—even notices) the "business logic" and can maintain their focus where it belong, on the language constructs being illustrated; and
- has some degree of usefulness for the construct being used.

The last point is the one that many more informal language docs often fall flat on. For instance, basic object orientation examples frequently are about `Person` or `Employee` objects. This is fine, as far as it goes, of showing a structlike class using a concrete(-ish) thing that is familiar and simple, but the question immediately arises: "why not just use a struct?"

`Person` objects (people) don't have obvious real-life operations everyone will be familiar with to demonstrate (a `.date-of-birth` property being embroidered with `.age` and `.birthday` is about as fancy as you can get without starting to make assumptions!). In his seminal writing on object orientation in Perl 5, Damian Conway used dog tags as a real-world thing whose `DogTag` class had an obvious has-a relationship with `Person`; but while dog tags have the additional advantage of some novelty (in terms of code examples, anyway) beyond the simplicity and familiarity, the obvious and interesting operations on them were much more limited than the geometric shapes provide.

In contrast, modern object orientation was developed in no small part by early computer graphics researchers, and problems involving geometric shapes are to this day frequently solved using object-oriented paradigms. Fixed 2D points may still be simple enough to ask "why not a struct?", but even a real-world thing as simple as a rectangle begins to have real utility with methods—and, lest the reader not be aware of this little dive into CS history motivating objects, we give a `.area` example to show this. The reader, presumably, will instantly see the possibilities of `.perimeter`, `.height`, and `.width`, and might be sparked to think about whether and how other possibilities like `.move` and `.scale` could be reckoned with as well.

One additional consideration to keep in mind: the way the tools for these docs work, we write most of our docs in large, essay-like files on well-defined topics, but it is entirely possible that the reader will, through the search facility, see only a small section out of context. This further constrains the examples, as where in a book one might develop and interesting example and continue iterating it as demonstrating new language features pulls in more behavior, in our case we have to write examples that are sensible and useful even if the reader hasn't seen the prior and following code examples at all.

Correctness, clarity, conciseness and coherence are the _sine qua non_ for these docs. Verve and pizzazz are certainly lovely stretch goals (and not ones we eschew), but they do have to take a back seat to the primary utility of the Perl 6 docs as a whole.

And a last point: the docs are in a GitHub repo in their entirety, and we are always delighted to incorporate good new content. That includes rewriting a "boring example" into something more interesting—provided it adheres first and foremost to the original purpose, and doesn't turn into a display of programming cleverness.

**Comment by JJ** [comment]
There's an issue that asks to focus on intent, not syntax #1748. I opened it and, after not raising a lot of enthusiasm, I closed it again. There are several problems with your request, and I'm not even going to get into what is boring and what is not. I'll just reiterate here what @treyharris has said, since I agree with him:
> the docs are in a GitHub repo in their entirety, and we are always delighted to incorporate good new content. That includes rewriting a "boring example" into something more interesting—provided it adheres first and foremost to the original purpose, and doesn't just turn into a display of the author's programming cleverness.
