### ISSUE TITLE
Repo is not clean on case-insensitive file systems

### ISSUE THREAD

**Issue by lizmat** [perl6/doc#2749]
## The problem

There apparently is a doc/Type/int.pod6 and an doc/Type/Int.pod6, which clash on case-insensitive file systems, such as is the default in MacOS.

## Suggestions

Move the doc/Type/int.pod6 to maybe doc/Type/native-int.pod6 ?

**Comment by lizmat** [comment]
Fixed with 161669df4f

**Comment by JJ** [comment]
Sorry, but I'm reopening this. I would very much like a different solution to renaming, which opens up all sorts of problems. If it's going to be only this file, we can hack something in to make it work with a different name, like using the script that generates the actual pages to do that for us. But doing it this way would reopen the just-closed #935. I'll reopen that anyway, and see what I can come up with, but any help will be appreciated.

**Comment by Altai-man** [comment]
I am :+1+ for some other solution. Isn't MacOS case-insensitive, but case-preserving? If not, can it somehow be configured for the case?

**Comment by JJ** [comment]
@Altai-man I've pushed another solution already. The problem is that any solution would require some changes by the user. Some of them include
* Source filters, that will change name of the file when checked out and in again. Problem is these have to be installed in the repo.
* Creating a case-sensitive filesystem by the user.
Being htmlify.p6 in the state it is, one hack more is not going to break it... So I said, what the heck...
