### ISSUE TITLE
type graph PNG on http://doc.perl6.org/type/Any is unreadable

### ISSUE THREAD

**Issue by daxim** [perl6/doc#282]
size of http://doc.perl6.org/images/type-graph-Any.png is only 288 pixels

**Comment by AlexDaniel** [comment]
I'll close this in favor of https://github.com/perl6/doc/issues/246

Basically the only way to make such PNG images readable is to increase the size. I don't think that we want to do that.

Instead, we should have links to SVG versions. In fact, if you change your link from
http://doc.perl6.org/images/type-graph-Any.png
to
http://doc.perl6.org/images/type-graph-Any.svg
you'll see a nice zoomable version.

So I think that the problem here is not that PNGs are too small, but that SVGs are inlined and users have no way to view them separately (well, they can manually change the link to .svg, but that's kinda hidden).

Interestingly, you've also proposed this patch: https://github.com/perl6/doc/issues/283
I think that it fixes the problem (unless you want to argue that we should generate such **huge** PNGs). So that's another reason for closing this.

By the way, a few days ago there was a discussion about getting rid of PNGs altogether (main point being that everything has proper SVG support nowadays). I think that we are going to keep PNGs for now, but I am not sure if this will last forever. And that's just another reason not to generate bigger PNGs.
