### ISSUE TITLE
Eliminate unnecessary implementation details from EVAL.

### ISSUE THREAD

**Issue by lizmat** [perl6/doc#2822]
https://github.com/perl6/doc/blob/a795b55476b7841bd74383265d72eaa3e71c0421/doc/Type/Cool.pod6#L1434

Why are we showing the **exact** signature of `EVAL` here, rather than the functional parts?  This feels to me we're exposing implementation dependent internals.

**Comment by lizmat** [comment]
Especially the `proto` and the `is copy` are implementation detail, IMO.

**Comment by lichtkind** [comment]
you right in sence that its not the most important info for start of use, but nevertheless to me very interesting

**Comment by lizmat** [comment]
But you're not a typical user  :-)   For the people just interested in the function, it's showing parts of the inside of what should be a black box for them.

**Comment by lichtkind** [comment]
sure but in my mind perl is about treating users as adults, they know what a signature is

**Comment by JJ** [comment]
The problem is that if you don't follow the exact signature you open the
Pandora box of what to do exactly: simplify? Change variable names? Merge
multis? There's no single better way to do it. And then an additional
problems is to maintain it. What if you merge multis and one of the multis
changes? Even if it's an implementation detail, you can't fail by sticking
to the original.  You might need an additional  explanation of what's spec
and what's not, but that's an order of magnitude easier to maintain.

**Comment by JJ** [comment]
Additionally, if the signature in the code and the documentation differ,
you don't know if it's by choice of who wrote the documentation or by
drift. You might hide (or expose) implementation details in the
documentation, but my experience so far is that keeping the signatures the
self same as in the implementation is what gives you the least headaches.

**Comment by lichtkind** [comment]
yes, its not in first interest for beginners but should be there. but i think its even helpful for for beginners showing them what is important to understant. i think normal beginners with dignity can ignore such info when they know what its about but no understand certain type names

**Comment by lizmat** [comment]
FWIW, I think this not the best way to do this: the documentation is about Perl 6, and not about the Rakudo Perl 6 implementation.  But I get your point.  So closing.

**Comment by JJ** [comment]
El mar., 21 may. 2019 a las 11:43, Elizabeth Mattijsen (<
notifications@github.com>) escribió:

> FWIW, I think this not the best way to do this: the documentation is about
> Perl 6, and not about the Rakudo Perl 6 implementation. But I get your
> point. So closing.
>
It's very likely that it's not the best, I don't claim it is. But I can't
think of a better alternative. Ideally, roast would include also signatures
so that we really know what's spec and what's not, but inferring signatures
from a bunch of roast tests (since we know synopsis is no longer the
reference) might be even more difficult, not to mention there are signature
cases that are not tested (either in roast or in Rakudo).
Additionally, Rakudo is not documented and it will not be. The alternative
to not documenting something as implementation-dependent is often not to
document it _at all_.
In general, the current rules of thumb are not a global optimum; probably
not even a local optimum. But barring the appearance of something better,
that's what we have and we'll kind of have to go with it.

**Comment by jnthn** [comment]
Probably there are a few signature features that we could consistently rule as an implementation detail that need not be represented in the documentation, such as `is copy` and `is raw`.

**Comment by JJ** [comment]
Hi,

El mar., 21 may. 2019 a las 12:09, Jonathan Worthington (<
notifications@github.com>) escribió:

> Probably there are a few signature features that we could consistently
> rule as an implementation detail that need not be represented in the
> documentation, such as is copy and is raw.
>
That's right, yes. Maybe open a new issue for that? We could even create an
xt test to check that it's not done in general...

**Comment by lichtkind** [comment]
allright but i dont think that an official interface to a method is rakudo specific

**Comment by lizmat** [comment]
> On 21 May 2019, at 12:09, Jonathan Worthington <notifications@github.com> wrote:
> Probably there are a few signature features that we could consistently rule as an implementation detail that need not be represented in the documentation, such as is copy and is raw.

“proto” I think is also an implementation detail.

**Comment by lichtkind** [comment]
good to that i would agree thats not doc relevant
