### ISSUE TITLE
small edit in first please

### ISSUE THREAD

**Issue by p6steve** [perl6/doc#2877]
## The problem

from here 
https://docs.perl6.org/routine/first

this line
<<Besides, starts from the :end and returns the :kv in a list; the key in this case is simply the position it occupies in the Seq.>>

is a non sequitur - it is quite incomprehensible/out of place

## Suggestions

it should be moved up immediately above this line
<<From version 6.d, the test can also be a Junction:>>

**Comment by uzluisf** [comment]
While I understand what's going on, it took me sometime to put it in a semi-coherent way. I reworded it:

> Besides starting from the `:end`, the `:kv` causes the return of a list where the *key* is simply the position the matched first item occupies in the `Seq`.

---
At first I thought the paragraph was redundant since `:end` was already explained and `:kv` is only a search away. However it now makes sense given that one may wrongly assume that the use of `:end` alters the position of the item when in fact, it does not. Thus, `:kv` will return the position (alongside the item itself) the first matched item originally holds in the `Seq`, regardless of `:end`.

```
> my @a = (1, 2, 7, 9, 10)
[1 2 7 9 10]
> @a.first(*%%3, :kv)
(3 9)
> @a.first(*%%3, :end, :kv)
(3 9)
```
