### ISSUE TITLE
Site formatting seems to have been disrupted

### ISSUE THREAD

**Issue by ajs** [perl6/doc#2911]
## The problem

Perl Doc site is rendering text BELOW the background image rather than over it, making it appear that every page is empty.

![perldocmissing](https://user-images.githubusercontent.com/98660/61578633-315efa80-aac8-11e9-9fb7-2620c23d7a47.jpg)

**Comment by JJ** [comment]
Thanks for the report. I will try and deploy the fixed site ASAP

**Comment by treyharris** [comment]
Hey @JJ — Unless I’m mistaken, I think you tagged the wrong issue with commit 58b9ef0 ... it added the fallback doc site [`perl6docs.github.io`](https://perl6docs.github.io) but didn’t fix the formatting issue mentioned above. Yet it _is_ fixed. (I noticed it myself yesterday but saw it was fixed in the github.io version so didn’t worry about it further.)

Bisecting and htmlifying would take literally days on my machine (okay, maybe just hours if I guessed well about a last-known good) and I don’t see an obvious commit that fixed it, but I suspect you know which one did. Could you mention it here and re-close the commit so it’s documented?

Thanks!

**Comment by treyharris** [comment]
(If I had to guess, it was commit e93988ac2befe95a245040ae453baac49d90fb06, but that would only be a guess.)

**Comment by JJ** [comment]
The problem had been solved before the issue was created. I just piggybacked the mention to the fallback site (which was working by then) in the README to close it, because it's convenient to close issues with commits. Yes, it was closed with that, commit, or actually with the deployment of the site after that commit. So... closed with e93988a.
