### ISSUE TITLE
｢cross｣ is not documented

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#382]
Which is an “English” version of ``X``.
```perl6
say cross (1,2), (42,69), with => &[=>]
```
```
(1 => 42 1 => 69 2 => 42 2 => 69)
```

While you're at it, don't forget to document ``with`` named argument in [zip docs](http://doc.perl6.org/routine/zip#class_List)

**Comment by AlexDaniel** [comment]
```
<perlawhirl> there should also probably be a link to 'cross'
             from 'X' (and vice versa)... same goes for 'Z' and 'zip'
```

**Comment by gfldex** [comment]
ENOSPEC, issued as https://github.com/perl6/roast/issues/165, still we need to wait for the spec to get a test. Since there are two unrelated edits, I will remove sub cross with https://github.com/perl6/doc/commit/b101e5e439. This can be reverted as soon as roast was updated.

**Comment by AlexDaniel** [comment]
Huh? I am not sure if this makes any sense.

We already have ``zip`` documented, I see no reasons to assume that ``cross`` should work differently than it does right now (that is, similarly to ``zip``). Nonexistence of tests in this case is *clearly* a roast issue.

If we were going to remove all things that are not tested then half of the docs would not be there. No, just file roast issues, leave the docs alone (unless you have reasons to assume the feature is going to change, and if that's the case, please link to the discussion).

**Comment by gfldex** [comment]
Yes, at some point, when other brave folk go and implement Perl 6, we will find out that plenty of subs and methods are doced but not tested. A very small fraction of the docs will need to be removed. We have removed or changed stuff before, because it was outdated or never planned as a language feature and we will have to do it again (one of them is dd, so I am guilty as any). However, there is no reason to make the situation worse by letting things slip through the cracks.

We had this discussion before. If we don't add stuff to roast first and then doc it, we will leave broken code/modules behind. Your exaggeration is not proving your point. Quite the opposite.

**Comment by jonathanstowe** [comment]
I did think about this when I merged this,  ```cross``` is pretty much the same as ```zip``` in this regard and is implemented as:

```
my &cross := &infix:<X>;
```

So the tests for ```X``` are the tests for ```cross``` too :)

**Comment by AlexDaniel** [comment]
But it is a fꝌ⪏ᣙ╃넌g ``cross``!!? It is as fundamental as ``zip``, what makes you assume that it might change?

We are not letting things slip through the cracks by creating issues in roast. As simple as that.

Sure, let's remove untested features from the documentation if there's something unclear about them. But not ``cross``.

**Comment by AlexDaniel** [comment]
Reverted in 1dd3004d2717a827a87c604fa7b98d9cd7c6654f, therefore closable.
