### ISSUE TITLE
triangle reduce missing

### ISSUE THREAD

**Issue by daxim** [perl6/doc#402]
I was reading <https://perl6advent.wordpress.com/2009/12/23/day-23-lazy-fruits-from-the-gather-of-eden/> and there was mention of `[\~]` operator. I remembered that this is composed and that `~` is string concat.

I did not know how to look up the rest; I asked and was given its name, triangle reduce. Neither <http://doc.perl6.org/routine/reduce> nor <http://doc.perl6.org/routine/%5B%20%5D> explain the triangle.

**Comment by AlexDaniel** [comment]
Some parts for it may be taken from [S03](http://design.perl6.org/S03.html) (search for “triangular reduce”)

**Comment by gfldex** [comment]
Reduction operators are documented in http://doc.perl6.org/language/operators#Reduction_Operators . Providing a full list of all meta operators would be a mile long. Most concrete meta operators are generated at compile time (at first use) and they can be chained. We would end up with a mile long mile wide list of operators. I agree that it does require in deep explanation what will hopefully be done by the Perl 6 book. Sending some nagging Larry´s way may help.

I'm closing this as it's documented already.

**Comment by AlexDaniel** [comment]
@gfldex While I agree that it is actually documented, don't you think that the documentation is a bit lacking? Compare what is written on http://doc.perl6.org/language/operators#Reduction_Operators and on http://design.perl6.org/S03.html#line_4775. I think that what we have in S03 is a bit more informative, mostly because of the provided example.

Does anybody feel the same?

**Comment by coke** [comment]
I am pretty sure nagging is not going to help anything.

**Comment by gfldex** [comment]
There are millions of children for whom nagging works very well, as any retailer will confirm.

My problem here is that meta-operators are a concept and subject of CS. So is iteration. If we go now and explain the concept of meta-operators, should we also explain the concept of iteration?

The Docs are the documentation of the language and therefor should list all features of the language and explain them unless the explanation would not provide any value to the audience. What leaves the question, who the audience is. We don't have a clear definition here (and maybe never will) what must lead to disagreements. As this thread shows.

I'm a bit concerned with making the docs to stuffed with redundant information (both as actually being twice in the Docs and repeating concepts that should be common knowledge to one who calls herself programmer), producing something that someone has to read but can't because it's way to much to get done in a reasonable time.

I made myself a preview renderer that creates one big html-file from all the pods. That file is already 1.9M big and keeps growing. Somebody has to read all that stuff. And that somebody may be you after next Christmas because we have to make sure that we have any changes, deprications (I'm quite sure we missed some already) and additions in Perl 6.d made it into the Docs. If maintenance becomes a burden it may just not happen.

So I would vote on being a little brief on the explaining side and with examples but I wont stop @AlexDaniel from being verbose if you got the time to improve the meta operator section and keep it in order for the next few years.
