### ISSUE TITLE
Constant: with or without sigil?

### ISSUE THREAD

**Issue by jjatria** [perl6/doc#416]
The docs are currently vague on the use of sigils in constants.

In [5to6-nutshell](http://doc.perl6.org/language/5to6-nutshell#constant):

> In Perl 6, constant is a declarator for variables, just like my, except the variable is permanently locked to the result of its initialization expression (evaluated at compile time).
>
> So, change the => to = , and add a sigil.

But [some](http://doc.perl6.org/language/terms#Identifier_terms) [examples](http://doc.perl6.org/language/syntax#Barewords_%28Constants%2C_Type_Names%29) do not actually use sigils, and in [Terms](http://doc.perl6.org/language/terms#Constants) this is explicit:

> Constants are declared with constant and do not require a sigil. The RHS is evaluated at compile time, what may be too early to make sense.

So, regardless of whether they are _required_, I think the docs should at least be consistent in what they recommend, and this should probably be reflected in the examples.

Thoughts?

**Comment by jjatria** [comment]
[Sigilless variables](http://doc.perl6.org/language/variables#Sigilless_variables).

Also relevant?

**Comment by gfldex** [comment]
There is no recommendation possible because sigils provide interface as explained all over the place (because the behaviour provided by a sigil depends on context). No sigil is also a sigil (implicit binding) but 5to6 is a bad place to explain that. The recommendation for one who wants to port Perl 5 code will most likely make sense.

EWONTFIX, closed
