### ISSUE TITLE
Provide a utility script to find and replace all Texas-version operators in a file

### ISSUE THREAD

**Issue by tbrowder** [perl6/doc#529]
The consensus is to use only the unicode variant of Perl 6 operators.  A utility script to find any Texas-variant operators in a file and, optionally, replace  them will be useful as a build-check tool as well as a developer tool.

**Comment by AlexDaniel** [comment]
You mean that we can have a test for that? (https://github.com/perl6/doc/issues/625)

Or that somebody has to write a module that will modify the files? (not a doc issue)

As for the documentation, I think that we should use Texas versions of operators as much as possible, simply because these are typically more readable. In fact, I even think that we should use ``‘’`` instead of ``''`` because people will often be copying the snippets into ``perl6 -e``.

If you really care about this, perhaps you can get some people to vote or something.

**Comment by Altai-man** [comment]
If it's about module to replace ascii to unicode using this table: https://doc.perl6.org/language/unicode_texas#Other_acceptable_single_codepoints - then I can try to do this.

**Comment by AlexDaniel** [comment]
@Altai-man any progress? ;)

**Comment by Altai-man** [comment]
@AlexDaniel I was busy with examples compilation and some side work. I hope to start it today/tomorrow.

**Comment by Altai-man** [comment]
I've created https://github.com/Altai-man/p6-Texas-To-Uni
Some info... We need to distinguish between code and string literals and don't change literals(NYI). Our texas-to-unicode table has duplicates. Testing is a must. Pull requests are welcome.
This script is still less than awesome, but I'd spend some time soon to make it better, so this issue can be closed.
