### ISSUE TITLE
cannot search for glossary items in search

### ISSUE THREAD

**Issue by coke** [perl6/doc#582]
e.g. "LTA"

**Comment by Altai-man** [comment]
I implemented this, but there are problems with Glossary at all.

While editing I found many problems of such types:
1.Empty entries. Is it really needed to point to them with search, if there are no text anyway?
2.Obvious entries. There are entries like "OS", "OOP" or "True" - should we really explain this? It's Perl 6 docs, not encyclopaedia.
3.Not really related to Perl 6 entries. It mostly relates to IRC section. Of course, some abbreviations are related, like "TMTOWTDI", but the meaning of, for example, "AFAIK" or "DRY" user can easily google for himself/herself.
4.Entries with names. It has meaning to have names like "Larry Wall" in the glossary, for sure, but should they be searchable as a part of language documentation?

As for me, many entries should be removed at all and not every item from glossary should be searchable.

**Comment by AlexDaniel** [comment]
1. We should just write the description for every term. See https://github.com/perl6/doc/issues/622
1. We have to decide here. Either we provide a link to wikipedia for every obvious term, or we remove them completely. However, looking at this, I think that we should go with former:
>  I want p6doc and doc.perl6.org to become the No. 1 resource to consult when you want to know something about a Perl 6 feature, be it from the language, or built-in types and routines. I want it to be useful to every Perl 6 programmer.
> -- moritz

1. ¯\_(ツ)_/¯
1. ¯\_(ツ)_/¯

Feel free to remove some entries.

**Comment by Altai-man** [comment]
@AlexDaniel, okay then.
For 1: if it's classes or roles, we have them already documented, they are: Callable, Code, Container, Cool, List, Module, Package and Scalar. As for me, it should be removed, but as just some quick explanation of type, it can be useful, I suppose, so I will not touch them. They will be indexed.
2.I'll insert links to Wikipedia for every obvious term in the commit. They will be indexed.
3.I'll remove some obvious items, they can always be returned anyway.
4.I will not include names in the index unless someone says otherwise.

**Comment by Altai-man** [comment]
Closed with https://github.com/perl6/doc/commit/3fda0592ce30ecaf442353a930259aae69e07da6
