### ISSUE TITLE
Space after comma

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#624]
Is there any reason to write ``1,2,3`` instead of ``1, 2, 3``?
I'd say that we should always put space character after commas.

**Comment by AlexDaniel** [comment]
So I used this to find all such occurances: ``grep -PR ',[^ ]' *``

The output was huge, but now it is much shorter.

So the situation is much better now, but I can't say that the issue is fully resolved. Can anybody take a look?

**Comment by Altai-man** [comment]
The grep expression above contains many false positives, due to Perl 6 syntax. It includes cases like
```
say split(<; ,>, "a;b;c,d", :k).perl;
```
or signatures like this
```
getservbyname NAME,PROTO
```
or even pod links like this:
```
=head2 X<given as a statement|control flow,given statement>
```

There are places in the examples, when we don't have a space after comma, but if we fix that, pretty formatting will be changed. I suppose, your commit closed this issue entirely.

**Comment by AlexDaniel** [comment]
OK, then we can close this. But see https://github.com/perl6/doc/issues/666.
