### ISSUE TITLE
Inconsistent use of "methods" and "routines"

### ISSUE THREAD

**Issue by xdg** [perl6/doc#638]
I noticed in docs for [class Method](https://doc.perl6.org/type/Method) that most sections are "Routines supplied by class..." but "Methods supplied by role Callable". 

In the "Routines" section of the docs, there seems to be no consistency with the distinction in the type docs.  E.g. "arity" is listed as a "Routine supplied by class" in the type docs for Method, but as "method" in the Routines page, whereas "assuming" is listed as "Method supplied by role" in the type docs for Method, and as a "method" on the "Routines" page.

Having different terms implies significance, but the inconsistency implies maybe no significance.

I think docs needs to pick one term or another and use it consistently.  Unless there is significance to the term "Routine supplied by...", I think saying "Method supplied by..." for both classes and roles would be more consistent and be easier to understand for people coming from other languages.

Then the Routines page can roll up all routines (method or not) and indicate their types (as it does).

**Comment by zoffixznet** [comment]
It might be tricky (or needless) to name sections by what they list, as for example [this one](https://doc.perl6.org/type/Method#Routines_supplied_by_class_Mu) lists both the sub form of `defined()` and the method form of `.defined()`. And [this one](https://doc.perl6.org/type/Method#Routines_supplied_by_class_Routine) lists traits in it as well as methods.

Since traits and methods *are* types of routines, at least factually the sections are correct. It's just the consistency is the issue. I think always naming sections 'Routines supplied by...' would be fine.

**Comment by AlexDaniel** [comment]
What about “routines and methods” or “routines / methods” or something like that?

**Comment by pmichaud** [comment]
I agree there should be consistency.  Since classes can supply any of methods and/or subs (and there are cases where the docs identify things as "traits"), I suspect using the generic `Routine` is the most correct from a language point of view.

I suspect this is not an exhaustive list, but classes/roles/grammars can document things that include terms such as "sub", "method", "trait", "regex", "token", "rule", and "submethod" and the generic way to refer to all of these is likely "routine".  (`Routine` is the common superclass for all of these.)

**Comment by xdg** [comment]
I'd prefer more specificity.  Assuming that "Routines provided by" refers to methods provided by subclasses, then I'd much rather the term "method" explicitly.  If traits or other things are inheritable (apologies -- I haven't reached those docs yet), then I'd like to see "Traits provided by..." or whatever.  The more specific and correct and consistent the documentation, the easier it is for new readers to stay oriented.

**Comment by JJ** [comment]
The problem here that some routines can behave either as methods or as subs, depending on the context. That is the case for `mkdir` mentioned in #1867. The problem is that they are only indexed as either, not as both.

**Comment by zoffixznet** [comment]
> some routines can behave either as methods or as subs

It's worth noting that's not just because there are both sub and method forms of some routines, but that both Method and Sub objects in Perl 6 are of type Routine, so it's valid to call both of them a "routine":

```
<Zoffix__> m: say Method ~~ Routine
<camelia> rakudo-moar 97677a792: OUTPUT: «True␤»
<Zoffix__> m: say Sub ~~ Routine
<camelia> rakudo-moar 97677a792: OUTPUT: «True␤»
```
