### ISSUE TITLE
revert font change

### ISSUE THREAD

**Issue by coke** [perl6/doc#652]
36e44716cd4ab8f3f0d557fdfc0ea7f007a9c8ea picked some new fonts that I really don't like; can we have a discussion about reverting this or picking new fonts?

**Comment by AlexDaniel** [comment]
+1 for revert. Can't see what was wrong with previous fonts, and I also dislike the use of cdn there.

**Comment by raiph** [comment]
Zoffix++ for all the great stuff you do. Please don't let discussions like
this bum you out.

I don't consider this a bikeshed topic. I request patience from anyone who
does.

Although I strongly dislike the overall typographic impact of 36e4471
<https://github.com/perl6/doc/commit/36e44716cd4ab8f3f0d557fdfc0ea7f007a9c8ea>
 on my system, I wasn't going to say anything. Maybe it was just an interim
step on the way to greatness. Perhaps things looked terrible on my system
but not others'. Etc. But I'm glad Coke++ said something.

I don't care whether the commit is reverted, cherry picked, or left in
place and further developed. Provided it isn't left as is I'll be happy.
(If it *is* left as is for a while I'll get over it even though I think
it's really ugly on my system.)

There's a lot more to the typographic changes in Zoffix's commit than just
font choice. Maybe I/others would like the font choice if it were not for
some of the other typographic changes as they manifest on my/their system.
Or vice-versa -- maybe I'd like the other changes if it weren't for the
font. Hard to say.

Furthermore, what each end user sees presumably varies. I don't think I've
used CSS in over a decade but it used to be that one specified lists of
font alternates that were then matched against an end user's system.
Additionally, users can specify their own preferences that can sometimes
override a stylesheet or interact with it in surprising ways.

To simplify, I'll momentarily ignore everything but a supposed "ideal font".

In Damian's On The Shoulders Of Giants presentation he flips back and forth
for a few seconds between almost identical displays, one of Perl 6 code,
the other Perl 5 code.

(Please spend 15 seconds reviewing this if you really want to understand
what I'm writing about. The first time he does this is 7 minutes 30 seconds
in:
https://www.youtube.com/watch?v=Nq2HkAYbG5o&index=10&list=PLRuESFRW2Fa77XObvk7-BYVFwobZHdXdK#7m30s
)

Simplifying a little, the only three differences between the two displays
are syntax (5 vs 6), color (white vs yellow), and font. I'll ignore the
first two differences.

I much prefer the font he uses for the Perl 6 code. (Do you?)

So, as a strawmanish proposal, I suggest we ask Damian what it is and adopt
that at least for displaying Perl 6 code. (Strawman*ish* because I mean
this as a reasonable proposal.)

As a broader strawman proposal, I suggest we pick a serif and a san-serif
font from
https://www.theguardian.com/theobserver/gallery/2013/sep/14/the-10-best-fonts
as the standard fonts for non code text for all Perl 6 materials.

(This strawman is without the *-ish* -- I don't really mean for us to
actually pick two of these 10 but rather pick any of the world's bazillion
fonts that are even better for our needs.)

I don't know if these "proposals" are at all realistic. It used to be that
one can't just arbitrarily pick a font for web content -- it has to be on
end-users' systems. And there were licensing issues too. Do these
complications still apply?

The foregoing proposals are for an "ideal" font. Which just leaves all the
other stuff Zoffix++ was working on in their commit...

So, for a final strawman proposal I suggest we just ask Damian, who's
clearly great at presentation, to write up his typographic advice for all
things Perl 6 and then try to follow his advice. Again, this is just a
strawman proposal.

-- 
raiph

**Comment by zoffixznet** [comment]
> Zoffix++ for all the great stuff you do. Please don't let discussions like
this bum you out.

I had "Designer" in my my job title for the last 8 years. People wanting [sometimes horrible] change is part of the job I'm long used to :smile_cat: So it's not bumming me out.

As I've mentioned on IRC, I'm fine with the commit being reverted or changed, but I'll step away from this discussion and making that change, as I'm a bit busy at the moment.

Good luck :)

**Comment by raiph** [comment]
To TL;DR the discussion thus far, everyone who has commented is either neutral or +1 toward 36e44716cd4ab8f3f0d557fdfc0ea7f007a9c8ea being reverted or changed.

At least Zoffix and I, who have both been professionally involved in design (I was head of marketing for two typographic software companies) would both like to see typographic improvement over what we have. His ideas are embodied in the commit. Mine are in my previous comment.

**Comment by jonathanstowe** [comment]
fwiw, as someone who probably shouldn't be let anywhere near a design decision, I don't have a problem with the font as it is rendered in my browser.  It works nicely for body text, and slightly less so for bold titles and so forth (to my admittedly just woken up eyes,) I suspect that might be related to the way that they font is implemented or rendered in Linux Chrome rather than the typeface itself.

In a purely subjective, abstract sense, I find the font to be friendly but still serious, I could do with the bold being a little less bold but I can deal with that.

So I'd go with sticking with this one, personally.

**Comment by AlexDaniel** [comment]
@jonathanstowe thanks.

Can somebody else speak up so that we have a better picture?

**Comment by stmuk** [comment]
I've looked at the new fonts and I'm not that keen but I don't feel
strongly enough to revert it.


On 1 July 2016 at 12:55, Aleks-Daniel Jakimenko-Aleksejev <
notifications@github.com> wrote:

> @jonathanstowe <https://github.com/jonathanstowe> thanks.
>
> Can somebody else speak up so that we have a better picture?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/perl6/doc/issues/652#issuecomment-229928269>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AEUuY75OfzeOr6G5SqHDp4sX4kcQAXl3ks5qRQAvgaJpZM4JBqVK>
> .
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by stmuk** [comment]
Also meant to say that if we go with this then examples.perl6.org also
needs updating.

On 1 July 2016 at 13:22, Steve Mynott <steve.mynott@gmail.com> wrote:

> I've looked at the new fonts and I'm not that keen but I don't feel
> strongly enough to revert it.
>
>
> On 1 July 2016 at 12:55, Aleks-Daniel Jakimenko-Aleksejev <
> notifications@github.com> wrote:
>
>> @jonathanstowe <https://github.com/jonathanstowe> thanks.
>>
>> Can somebody else speak up so that we have a better picture?
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/perl6/doc/issues/652#issuecomment-229928269>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AEUuY75OfzeOr6G5SqHDp4sX4kcQAXl3ks5qRQAvgaJpZM4JBqVK>
>> .
>>
>
>
>
> --
> 4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>
>



-- 
4096R/EA75174B Steve Mynott <steve.mynott@gmail.com>

**Comment by pdl** [comment]
> So, as a strawmanish proposal, I suggest we ask Damian what it is and adopt
that at least for displaying Perl 6 code.

That is Monaco and we can put it in our stack but pretty much only Mac users will see it.

**Comment by pdl** [comment]
Open Sans itself is a perfectly usable font in the right context. But the way we're using it curently doesn't really play to its strengths. It benefits a lot from having space. It does light-weight large headers well too. To me, Roboto Mono is not a natural pairing: Roboto is a more Grotesque-inspired font whereas Open Sans is a humanist font. By way of contrast, look at MDN's mono stack, which complements their use of Open Sans as a body font.

I don't think it's especially fruitful to try to come to a clear decision about typeface in isolation; the choice of font interacts with the rest of the design so much on a text-heavy site like this. And right now the design of the site... I'm hoping it's not a permanent design decision, as it feels gaudy and unripe. So in the short term I don't really care what font is used so long as it's vaguely readable. The main practical consideration at this point would be picking a mono font which covers non-ASCII operators.

In the medium-long term, I would hope we could have a discussion about:

- What we want to convey (or avoid conveying!) with our design
- What constraints our content puts on the design
- How important concerns like speed/bandwidth is to our users

And from there we might then commit to some overall design directions, e.g. keep the big rounded corners but aim for a geometric aesthetic, or perhaps go for something more lively with more organic fonts and lots of contrast. Or maybe we want the design to recede and the content to be the more prominent thing, in which case we would aim for a design which complements workhorse fonts with a more neutral palette.

I notice Zoffix has been working on marshalling the CSS into Sass which will I suspect help considerably.

**Comment by coke** [comment]
I'm fine with the font that's in the code samples; The font that is being used for headings & paragraph text  was the one I found problematic. I could probably live with just the header font changing at this point.

(also, -1 from me on the big rounded corners, but that's a separate ticket. :)

**Comment by CIAvash** [comment]
Overall, I think the changes made the site look slightly better, except for the headings("Open Sans Condensed").

I suspect people were seeing different fonts before this change. The default fonts our OSes used are probably different, because of the use of 'sans-serif' and 'monospace'.

And like @AlexDaniel I'm against the use of CDN, I think we should put the fonts on our own server if we want to use web fonts.

**Comment by AlexDaniel** [comment]
I reverted the changes, see commit https://github.com/perl6/doc/commit/f3fdd08e97dff685f12c337c3d15323c6f85e2ea. As I've mentioned in the commit message, I still think that we can improve what we have now (either by cherry-picking some changes from https://github.com/perl6/doc/commit/36e44716cd4ab8f3f0d557fdfc0ea7f007a9c8ea or by coming up with something new).

Perhaps it makes sense to propose your suggestions with *before* and *after* screenshots? This way we will all have a clear understanding as to what is going to change, and if these changes reflect the same situation that we see locally in our browsers.

**Comment by gfldex** [comment]
I would like to add to the discussion that I carefully picked to default fonts for my browser to suit my needs (4k screen). Sadly I can't force my fonts on websites anymore because quite a few web-"designers" believe that fonts are cool for icons. We can expect the vast majority of our readers to find the right settings to select a font for their browser to works well for them. Please let them do so.

**Comment by coke** [comment]
I'm OK with closing out this ticket.

**Comment by AlexDaniel** [comment]
The title says “revert font change”. That is done.

Please open a new issue if you think we need better fonts.
