### ISSUE TITLE
“Available in Perl 6, but, oddly, not yet documented.”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#656]
https://docs.perl6.org/language/5to6-perlfunc#use

It kinda is documented: https://docs.perl6.org/syntax/use

**Comment by gfldex** [comment]
It is one of those hen-egg-problems. To understand named arguments to use (that are not really arguments because use is not a Callable) one needs to understand `is export` and sub EXPORT. To understand the latter two one needs to know what `use` is for. Again, the docs are not the to be written book The Perl 6 Programming Language or Learning to Program with Perl 6.

Unless you got a good idea how to solve the hen-egg-problem, please close this ticket.

**Comment by AlexDaniel** [comment]
This ticket is about this sentence:
> Available in Perl 6, but, oddly, not yet documented. One assumes it works similarly, if not identically, to the way it does in Perl 5

First of all, it **is** documented. Secondly, what is this “one assumes it works similarly, if not identically”. Sounds like we have no idea what we are talking about…

So yeah, while you are right that there are other issues, this ticket is not about it.

I guess that we can just remove the sentence and link to https://docs.perl6.org/syntax/use instead.

**Comment by dha** [comment]
That should be ok. FWIW, as with a number of sentences like this, it was probably true when I wrote it, but may well have changed since, but neither I nor anyone else thought to change it in the 5to6 docs. If anyone has a good idea how raise that kind of red flag when a previously undocumented thing becomes documented, I'm open to suggestions... :-)
