### ISSUE TITLE
Use smaller width for triggering ToC-on-the-side layout

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#690]

**Comment by gfldex** [comment]
@media (min-width: 110em) {

Is the line in question. I don't have a 1050p screen so I can't fiddle with it to test it. Please keep in mind that 4/5k screen with UI scaling can make things complicated (that's why it's in em and not px).

**Comment by zoffixznet** [comment]
I don't really understand what benefit using `em` units gives.

Here're two screenshots from a 1440p monitor both with ToC-on-side default version and fonts scaled enough to trigger ToC-on-top layout, yet even with the latter, half the screen is still empty and the width is nearly the same. So it seems the media rule effectively arbitrarily affects whether or not you'll get ToC-on-side and not whether there's space to fit it on your display device.

FWIW, Bootstrap uses pixels for its media settings.

![untitled](https://cloud.githubusercontent.com/assets/5747918/16752689/9a52553c-47b1-11e6-9fd9-99c9bcde7261.png)
![untitled](https://cloud.githubusercontent.com/assets/5747918/16752858/e452a87a-47b2-11e6-8fba-9914fb9b299d.png)

**Comment by gfldex** [comment]
X11 is the only GUI where the user can tell the system how big his screen actually is, using the dpi section in the config. On any other system browser vendors use a heuristic to figure out what px actually means. See https://bugzilla.mozilla.org/show_bug.cgi?id=890156 if you want to know how much fun they have on windows to make font rendering work if there is more then one screen with different DPIs.

A 10px high font (there are web "designer" who believe that would be a good idea) is less then 2mm high on my 4k screen (i _have_ to use Stylish). The trusty 1280x1024 screen I also got will display them just fine. With 5k screens the DPIs are even higher and using pixels _for_anything_ makes even less sense. You can tell firefox to do it's own scaling, only for fonts. That kind of works but then odd things happen with icons. Using pixels is already causing problems and the situation will only get worse as DPI go up (what else can display vendors "invent" these days?).

EM is the solution because as a unit it contains DPI. Further, any layout should be proportional to the font size, because of the human brain. We don't really do absolute measures.

There are indeed problems with big margins to the side of the center box. A box that is separating it's content from no other content. So the whole thing is redundant to start with. We need a redesign that is tested on small and big screens, with high and low DPI. That will take the better part of the week.

If you want it wider RIGHT NAOW, by all means setup a rule for Stylish. That's what User Styles are for.

**Comment by zoffixznet** [comment]
@gfldex you don't have to be a giant dick with your responses. I'm not a mind reader to know what you plan on working on next week.

**Comment by gfldex** [comment]
I do not plan to work on a redesign at all right now and the notion that you may want to setup a Stylish rule is genuine advice (in my eyes at least) because a redesign wont happen any time soon. It would be nice if you could refrain from calling me a "giant dick" in the future.

**Comment by gfldex** [comment]
The problem is valid and still unsolved. Therefore *reopen*.
