### ISSUE TITLE
Provide a .tar.gz version of documentation

### ISSUE THREAD

**Issue by Altai-man** [perl6/doc#718]
We need to create a .tar.gz to satisfy the index page's claim that "you can also download an offline HTML ... copy".

This issue is a part of TODO.

**Comment by Altai-man** [comment]
I'm not sure who exactly raised this issue(sorry), but still.

With a `.tar.gz version` we think about `p6doc` script and `doc/` directory to have an ability to type `p6doc something`, or `html/` directory and `app.pl` script to have an ability to start a local server with docs? Or both?

It is easy to write a command to `tar`, but it is important to know what exactly we need to archive. With every(or every 5-th, for example) doc build we need to remove an old version and generate new. And we need to add a link to this archive, maybe on `About` or even main page.

Currently, with `both` option an archive weight is about 10 mb.

**Comment by coke** [comment]
I believe the thought is just a file containing all the files in html/

**Comment by Altai-man** [comment]
Just in case: the actual command is `tar -czf perl6-documentation.tar.gz app-start app.pl assets/ html/ Makefile`.

**Comment by zoffixznet** [comment]
FWIW, I tried unpacking an archive of all the HTML files on Windows and there are numerous issues. The first is we have files which chars that are invalid on windows (like `<` and `>`). And also there seem to be some sort of encoding issues with files that have fancy pants Unicode chars in them:

![untitled](https://cloud.githubusercontent.com/assets/5747918/22702622/55838d62-ed2f-11e6-805b-c02877133994.png)

This is on Windows 7, unpacked with 7-zip, archive made with `tar -cvvf ...`

**Comment by JJ** [comment]
Only thing I can think about is to URI-encode filenames. Short of ditching
Windows 7, that is. Probably W10 won't have that problem.

**Comment by zoffixznet** [comment]
Also, all the assets have absolute paths, so search is busted and site is unstyled:

![untitled](https://cloud.githubusercontent.com/assets/5747918/22702998/9a68cd38-ed30-11e6-8a9a-28d993ab3a09.png)

**Comment by JJ** [comment]
The actual issue is creating the .tar.gz, doing so automatically or making one that works in Windows?

**Comment by zoffixznet** [comment]
Personally, I imagined the docs site being made into an SQLite database with something like (currently non-existent) Pod::To::SQL. Then instead of messing with tarballs the users would just download the snapshot of the database and `p6doc` could even have an option to be a local HTTP server to cater it (instead of just shoving the goods on the command line)

**Comment by fluca1978** [comment]
Why not tagging releases and let p6doc to download "stable" releases of the doc? They can be therefore served by a local server.
I don't see the point in having the docs within an sql database, since we can already download via git the exact version we need.

**Comment by stmuk** [comment]
This isn't anything to do with p6doc which works currently now using the source pod6 and doesn't need a copy of the HTML.  

There was another ticket suggesting p6doc become a web server as a workaround for now fixed speed issues which was recently closed. Personally I'd rather see this repo split out into pure pod docs, web site generation code and p6doc (command line) before more functionality is added (although I like the idea of SQLite and webservers in general). Neither do I want to see the p6doc command itself made slower with extra functions yet.

I don't  see why this is to do with a .tar.gz (which would be no use on Windows).

Everything is in place to create a one page flat HTML file using the current repo since it includes a dependency on  Pod::To::BigPage which will do exactly that if you just run "pod2onepage". 

So I assume the argument is where this single page is made available. Probably a good start would be to run "pod2onepage" as part of the web site build (if it doesn't do this already) and copy it to a location on the website.  I had thought of supplying it with Rakudo Star but I think it would be better to convert it to a PDF like

https://github.com/rakudo/star/blob/master/docs/perl6intro.pdf

(which also exists as a website)

**Comment by zoffixznet** [comment]
> I don't see the point in having the docs within an sql database, since we can already download via git the exact version we need.

You can only download the source files, which is kinda useless.

> So I assume the argument is where this single page is made available.

It's [already available](https://docs.perl6.org/perl6.xhtml) and is linked to from the first paragraph of the site.

**Comment by stmuk** [comment]
> So I assume the argument is where this single page is made available.
> 
> It's already available and is linked to from the first paragraph of the site.

So the ticket should be closed?

**Comment by JJ** [comment]
I'm all for closing 👍

**Comment by zoffixznet** [comment]
> So the ticket should be closed?

👍
