### ISSUE TITLE
named subroutine also could store in a named scalar 

### ISSUE THREAD

**Issue by songzan** [perl6/doc#77]
> my $x = sub double($y) { 2 * $y }
    sub double (Any $y) { #`(Sub|74224392) ... }
    > $x(2)
    4

**Comment by FROGGS** [comment]
What exactly is the issue?

**Comment by jonathanstowe** [comment]
That's the specified behaviour isn't it? http://design.perl6.org/S06.html#Named_subroutines

**Comment by paultcochrane** [comment]
I believe the issue is that it looks like this feature isn't documented.  However, it is actually documented in http://doc.perl6.org/language/functions#Functions_are_First-Class_Objects.  Thus I believe the ticket can be closed; if this is not the case, the ticket can be reopened with a clearer explanation of the problem.
