### ISSUE TITLE
“There is much good recent material on YouTube” – yeah, so many cool videos…

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#771]
I think that we have to be picky about such things. We already know that the error messages have to be awesome, I believe that there is no reason to have less than awesome docs. But look at this:

> Where can I find good documentation on Perl 6?

OK, so, someone is looking for **good** documentation! After two not very clear paragraphs we give the best that we have:

> There is much good recent material on YouTube but be careful to check any dates on webpages since much of the Perl 6 information on random websites found by Google is often outdated.

… What?… Well, OK. If that does not work for you:

> You could also try searching the Freenode #perl6 IRC channel log via Google

Seriously? How do you imagine this?

OK, humor aside, what can we do about it?

1) First of all, the best documentation is on https://docs.perl6.org (coincidentally, the website the user is currently on). That's it, that's the answer.

2) In the second paragraph we can say “You can also look at other resources listed on https://www.perl6.org/documentation/ page”. That is, if 1) did not work for you, then you can try one of these links.

3) If nothing works, “Feel free to ask your question on #perl6”. Also say how friendly and helpful we are, and that we are ready to answer all kind of questions.

**Comment by stmuk** [comment]
I don't understand your criticisms here.  Most of the Perl 6 documentation as found by google is poor, outdated documentation which will mislead the user. This is why the question is "good" documentation. 

"The most reliable information is to be found either under the perl6.org domains or directly linked from it." is quite clear.  It was phrased to include  examples.perl6.org as well as just docs.perl6.org.  It also includes any future subdomains (so we don't have to keep maintaining a list in the FAQ).

The user won't necessarily be looking at the doc.perl6.org website when reading this content since they could be reading docs from the command line.

Searching the IRC channel is good advice and not intended as a joke (and a specific link is given to do).  Most of the obvious questions have been asked and answered many times on IRC.

**Comment by dha** [comment]
> Most of the obvious questions have been asked and answered many times on IRC.

In that case, should these not be turned into FAQs? Not that I have any idea how often they should be asked and answered on IRC before being turned into FAQs at the moment...

**Comment by coke** [comment]
In general, questions from IRC should be considered for inclusion into the FAQ; of course. However, I doubt anyone is going to dig through months of IRC logs to figure out what these were, up to now.

Most of the people hacking on the site are in the channel, so we should keep our eyes open and if there's a common question (e.g. one I saw today (shortened) "Why moar, when parrot?"), someone can take the initiative and add it to the FAQ.

**Comment by coke** [comment]
@AlexDaniel - can you provide a PR changing the language in the FAQ for this to your liking?

**Comment by AlexDaniel** [comment]
OK, I can do that. Not promising to do it very soon though.
