### ISSUE TITLE
Search results should not display p5-to-p6 material first

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#792]
Many search terms display results p5-to-p6 guides as the *first items* on the list of results. This is LTA when you try to read the results and have to skip through the first entries, but it's even more annoying when you navigate to the wanted item with keyboard and have to key through these results all the time.

It's much more likely the person searching would want to read the P6 results, not P5-to-6 guides: there are programmers who come from other languages and even those who do come from P5 don't need to go to P5's guide to learn that the `accept` that was displayed second in the search results is the `accept` they likely want; or to have `listen` suggested when they search for `List`.

The P5-to-6 guides should appear last in the search results.

![p5](https://cloud.githubusercontent.com/assets/5747918/17365835/40539db4-5956-11e6-828e-c67dc068ffc9.png)

**Comment by Altai-man** [comment]
The actual problem is a bit harder.
Currently, our `sortBy` function just uses first letters, obvious. To make exact search first, to make one-letter results first, to solve this issue too, we need to completely re-think how we do the search results order, since current approach makes us unable to do any complex ordering.
I'm not sure about jquery completion plugin capabilities too.

**Comment by zoffixznet** [comment]
Not sure about one-letter results, but I was easily able to place 5to6 last. Thanks for pointing out the `sortBy`

**Comment by Altai-man** [comment]
Hmm, it seems like a partial solution for me, but if the issue is solved, then it is not bad.
