### ISSUE TITLE
in-range method is not documented

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#819]
Here is the example code of what in-range method is.

```
$ perl6 -e 'my $range = 0..3; say $range.in-range(1);'
True
$ perl6 -e 'my $range = 0..3; say $range.in-range(4);'
Value out of range. Is: 4, should be in 0..3
  in block <unit> at -e line 1
```

See also: https://github.com/rakudo/rakudo/blob/master/src/core/Range.pm6#L703-L706

**Comment by pmichaud** [comment]
This ticket gets a comment similar to the one I gave to (the original version of) #818 :  I don't know that "in-range" is properly a part of the Perl 6 language specification -- it may just be a Rakudo internals method that shouldn't be used outside of the Range class.  In particular, there are no roast tests for "in-range".

Pm

**Comment by pmichaud** [comment]
As a possible alternative, rather than not documenting the "in-range" (or "clone-with-op") method at all, they could be listed as being Rakudo internals methods not intended for use outside of Rakudo.

Pm

**Comment by jonathanstowe** [comment]
It's a strange one as it is only used in Date and DateTime  to check for out of bounds arguments and throw an exception.  Its basically ```($range ~~ $val) || die``` but with an OutOfRange exception.

**Comment by finanalyst** [comment]
From the perspective of language evolution, functionality created to 
overcome some limitation or is more convenient than the standard 
specification, points to how the language should develop in the future.

The specification and test suite are there to create portability across 
implementations. But if the methods are useful and are used by other 
programmers, then they will want them to work across all compilers.

Perl6 explicitly provides for extensions. Perhaps, these methods 
(internal to Rakudo) could be documented together with standard Perl6 
code that does the same thing, perhaps more slowly or less elegantly.  
That way, even if they are used with other implementations, it would 
only be necessary to include the extra code in the set up phase, rather 
than going through all the code to look for where they are used.

Good practice - of course - is only to use standard specification, but 
sometimes code is generated with no intent for it to be portable, only 
to find that it is more widely useful than originally intended.

Richard

**Comment by AlexDaniel** [comment]
So, uh, what does it mean?

Does it mean that we should document such things, but we should add a note that it is rakudo-specific and not part of the language?

**Comment by pmichaud** [comment]
On Sun, Aug 07, 2016 at 06:55:18PM -0700, Richard Hainsworth wrote:
>  From the perspective of language evolution, functionality created to 
> overcome some limitation or is more convenient than the standard 
> specification, points to how the language should develop in the future.
> [...]
> The specification and test suite are there to create portability across 
> implementations. But if the methods are useful and are used by other 
> programmers, then they will want them to work across all compilers.

On the other hand, sometimes (internal) methods are added to the 
implementation simply as scaffolding, with the expectation that they
may be removed or refactored later.  If we treat them as being "usable"
outside of the internals -- i.e., if we document them as being supported
by the language when that's not the intent -- that's akin to a commitment
that they will exist in all sibling and future implementations or that
there will be suitable deprecation cycles prior to their removal.

I'd prefer that such methods be clearly marked as "for internal use only",
so that they don't find their way into the (de-facto) language specification
more by accident than design.

In the specific cases given by #818 and #819, my first reaction upon
seeing the tickets was "that doesn't look consistent with the rest
of Perl 6" and "that almost certainly isn't a deliberate language
design choice", which is why I've called attention to it.

Pm

**Comment by gfldex** [comment]
Since we still don't have a way to make the transition from v6.c to v6.d, both for code and for the docs it would be ill advised to sneak internals in because they are useful. If you believe the method should be in v6.d provide a PR against roast. You can link the PR/RT here and reopen this issue. That the proper order to make sure things don't fall through the cracks.

ENOSPEC, closed

**Comment by AlexDaniel** [comment]
To me it sounds like using the new NOTSPECCED label is an even better way to make sure that it wont fall through the cracks.
If it some point we decide that it will never be documented, we will close it. But if at some point it is added to roast, we will not forget to write the docs. In other words, check again later!

Feel free to reclose if you think that we should not have an issue here.

That being said, maybe we should doc it: “**Do not use this! It is not even an experimental feature.**”. Again, if we decide that it is how we should document stuff like this, then with this new label it will be much easier to find it.

**Comment by jonathanstowe** [comment]
Maybe there should be a "meta-issue" to discuss where the line is drawn for un-specced items, and what the threshold for discovery of undocumented items should be.

**Comment by JJ** [comment]
There's a reasonable [use case here](https://github.com/rakudo/rakudo/blob/8c617cfa9e533983ccf2c3dd80b07e16849c6942/src/core/DateTime.pm6#L83). Maybe we should document it in this case. This kind if limbo it's in forces us to check from time to time...
