### ISSUE TITLE
http://doc.perl6.org/language/io and http://doc.perl6.org/type/IO should mention how to iterate over a file line-by-line.

### ISSUE THREAD

**Issue by shlomif** [perl6/doc#83]
http://doc.perl6.org/language/io and http://doc.perl6.org/type/IO should mention how to iterate over a file line-by-line. I mean:

```text
for 'sets.txt'.IO.lines -> $line {
    # Do something with $line
}
```

**Comment by paultcochrane** [comment]
An example was added to doc.perl6.org/language/io in f9032c07.  I don't know if it's appropriate to add an example about line-by-line iteration to the docs for the `IO` role, since the `lines` method is a method of the `Cool` class, hence I've added a note about line-by-line processing to the `Cool` documentation (in a6dbcf16bc8f1cc71e896de4356057927d5ff2b1).

**Comment by shlomif** [comment]
thanks!
