### ISSUE TITLE
BUILDALL is not searchable

### ISSUE THREAD

**Issue by titsuki** [perl6/doc#834]
BUILDALL is documented here
https://docs.perl6.org/language/objects#Object_Construction

**Comment by Altai-man** [comment]
Thanks, fixed with https://github.com/perl6/doc/commit/8f8e9b50228d559d22630e5b9dea012e135eb614
You are already in Perl 6 organization, so you can commit small changes to the master freely if you want.

**Comment by titsuki** [comment]
@Altai-man 
Thanks for your advice.
Honestly to say, I'm not entirely sure the indexing syntax.

For example
+ What's the difference between the four and which one is the best ?
  + `X<BEGIN|BEGIN (phasers)>`
  + `X<BEGIN|phasers,BEGIN>`
  + `X<C<BEGIN>|BEGIN (phasers)>`
  + `X<C<BEGIN>|phasers,BEGIN>`

+ What's the difference between the two and which one is the best ?
  + `X<-M> X<-A> X<-C>`
  + `X<|-M;-A;-C>`

**Comment by Altai-man** [comment]
@titsuki 
Indexing syntax is described at https://design.perl6.org/S26.html#Indexing_terms, but it lacks examples a bit. About your first question.
* First -> word "BEGIN" in the document and ability to search by "BEGIN (phasers)" phrase.
* Second -> word "BEGIN" and ability to search by "BEGIN" phrase under the category "phasers". It adds new category, just like "Method" or "Class", if it doesn't exist already.
* Third -> word "BEGIN" in the monospace(code-like) font(see third paragraph of https://design.perl6.org/S26.html#Example_specifiers) and ability to search by "BEGIN (phasers)" phrase.
* Fourth(you may guess now) -> word "BEGIN" with a monospace font and ability to search "BEGIN" word under the category "phasers".

You can omit a word on page, something like `X<|BEGIN (phasers)`. Personally, I'd prefer this variant. It creates invisible anchor to point search query. Also, you can include different search keywords under one `X<>` directive, just state all of them with a `;` splitter. It works with categories too, so you can write something like `X<category_foo,bar;category_foo,baz>`.

So, in your second question: first variant is a three search anchors with appropriate text showed on the page and the same search phrase. The second variant will not include any text on the page, it just creates three search anchors.

Also, you can turn `headN` paragraphs into search anchors, just using it like I did in fix commit for this issue.

To be honest, we have bits of rotten search anchors here and there(you pointed `-M -A -C`, for example), so review and fixes are very helpful and welcome. We don't have a single style(just like with output of examples) and it's okay because of TMTOWTDI, but bad-formatted phrases, words without context that are just search anchors are no good.

You can also ask me or other folks on #perl6 irc channel or in private on freenode, my nick there is `sena_kun`. And you can build and run docs locally(if you're on linux) to see how your changed were reflected.

**Comment by titsuki** [comment]
@Altai-man 
Thanks for your replay and neat explanation !
