### ISSUE TITLE
method dispatch:<..> appears to be undocumented

### ISSUE THREAD

**Issue by zoffixznet** [perl6/doc#970]
There are [some juicy method dispatch overrides](https://github.com/rakudo/rakudo/blob/a09c8dc99ef7ae60876ad7a7cc478f7e303eb804/src/core/Mu.pm#L658) available in Mu, but I don't see them documented.

They allow to mod how method dispatch occurs:

```
<ZoffixW> m: class Foo { method dispatch:<.+>(Mu \SELF: \name, |c) { say "cannot call {name} like that, bruh" }; }.+meow
<camelia> rakudo-moar a09c8d: OUTPUT«cannot call meow like that, bruh␤»

<ZoffixW> m: class Foo { method dispatch:<hyper>(Mu \SELF: \name, |c) { say "Calling {name} in hyperspace mode... Set phasers to stun!" }; }».test
<camelia> rakudo-moar a09c8d: OUTPUT«Calling test in hyperspace mode... Set phasers to stun!␤»
```

**Comment by jnthn** [comment]
I'd consider these something of a Rakudo-specific implementation detail rather than something to override. Note that in the past there was a `dispatch:<.^>`, which went away in terms of code-gen to solve a number of problems and make it more efficient. Also that `dispatch:<!>` is not reliably used; the call to it is optimized away into a direct reference to the private method at optimization time. While `.+` and `.*` are a bit too complex to code-gen directly, `.?` is certainly a candidate for doing so. Some day, somebody will probably want to optimize `dispatch:<::>` also.
