### ISSUE TITLE
Built-in Character Classes

### ISSUE THREAD

**Issue by adaptiveoptics** [perl6/doc#973]
The builtin character classes want to be documented

**Comment by adaptiveoptics** [comment]
did it

**Comment by AlexDaniel** [comment]
Is it a complete list?

**Comment by adaptiveoptics** [comment]
It was the POSIX list we talked about, taken pretty much verbatim from the
Perl5  docs, with some minor condensation. Was there more that should be
listed?

**Comment by AlexDaniel** [comment]
Uh, it is a bit complicated.

There is no ``<word>``, there is no ``<ascii>``. On the other hand, there are additional ``<ident>``, ``<ws>``, ``<ww>`` and ``<wb>``. Perhaps instead of calling them “POSIX Character Classes” we should call them “[Predefined Subrules](http://design.perl6.org/S05.html#Predefined_Subrules)” (just like design docs do).

**Comment by moritz** [comment]
Now only `<ident>` and `<ws> seem to be missing.

**Comment by AlexDaniel** [comment]
This discussion seems to be very important: https://irclog.perlgeek.de/perl6/2016-11-29#i_13650256

Seems like we have to have a clear distinction between character classes and subrules, even though it is basically the same thing?

**Comment by JJ** [comment]
Some relation to #1729?
