### ISSUE TITLE
perl-nbsp.t does not catch “Perl6”

### ISSUE THREAD

**Issue by AlexDaniel** [perl6/doc#993]
[Example](https://github.com/perl6/doc/blob/11552fea691714be840a09ee6637eeebd1641b65/doc/Language/traps.pod6#L485)

**Comment by tommystanton** [comment]
@AlexDaniel: Great catch!  I've noticed this from time to time.  Happy to see an issue created to track it. :+1: 

Also, I wasn't aware of `perl-nbsp.t`; glad we have that foundation. :grin:

**Comment by coke** [comment]
The naive fix for this causes failures on:

```
$ ack -C2 Perl6 doc/Type/Int.pod6

For a more detailed discussion, see
L<this blog post|http://perl6.party/post/Perl6-.polymod-break-up-a-number-into-denominations>

=head2 routine is-prime
```
(as an example; most of the no-space variants appear in links, or module names, or paths, and do not require fixing)

Trying to work around this by passing the pod6 files through "perl6 --doc" fails, because there's a bug in the --doc option that strips the non-breaking space and emits a regular space - so checking a rendered pod file means everything fails.

Checking manually, I found 3 instances where this was occurring, and inserted the appropriate spaces.

**Comment by AlexDaniel** [comment]
OK, then I guess we will just check it once in a few years. Alternatively there can be some test with the hardcoded number of current perl[56] strings in our docs (if anybody wants to add a link like this, he will have to increase that number). But that's probably not worth the trouble so yeah…
